package es.maps.programacion.fundamentos.es.androidfundamentosproyecto.sqlite.pojo;

import android.database.sqlite.SQLiteDatabase;

/**
 * Created by jvg63 on 07/12/2016.
 */

public class DatosPaisesDivisas {

    public static void datosPaisesDivisas(SQLiteDatabase db) {

        db.execSQL("DROP TABLE IF EXISTS divisas");
        db.execSQL("CREATE TABLE divisas (ID_DIVISA  PRIMARY KEY  NOT NULL  UNIQUE , ID_DIVISA2 , DIVISA_ES , DIVISA_EN )");
        db.execSQL("INSERT INTO divisas VALUES('AED','784','Dírham de los Emiratos Árabes Unidos','United Arab Emirates dirham')");
        db.execSQL("INSERT INTO divisas VALUES('AFN','971','Afgani','Afghan afghani')");
        db.execSQL("INSERT INTO divisas VALUES('ALL','8','Lek','Albanian lek')");
        db.execSQL("INSERT INTO divisas VALUES('AMD','51','Dram armenio','Armenian dram')");
        db.execSQL("INSERT INTO divisas VALUES('ANG','532','Florín antillano neerlandés','Netherlands Antillean guilder')");
        db.execSQL("INSERT INTO divisas VALUES('AOA','973','Kwanza','Angolan kwanza')");
        db.execSQL("INSERT INTO divisas VALUES('ARS','32','Peso argentino','Argentine peso')");
        db.execSQL("INSERT INTO divisas VALUES('AUD','36','Dólar australiano','Australian dollar')");
        db.execSQL("INSERT INTO divisas VALUES('AWG','533','Florín arubeño','Aruban florin')");
        db.execSQL("INSERT INTO divisas VALUES('AZN','944','Manat azerbaiyano','Azerbaijani manat')");
        db.execSQL("INSERT INTO divisas VALUES('BAM','977','Marco convertible','Bosnia and Herzegovina convertible mark')");
        db.execSQL("INSERT INTO divisas VALUES('BBD','52','Dólar de Barbados','Barbados dollar')");
        db.execSQL("INSERT INTO divisas VALUES('BDT','50','Taka','Bangladeshi taka')");
        db.execSQL("INSERT INTO divisas VALUES('BGN','975','Lev búlgaro','Bulgarian lev')");
        db.execSQL("INSERT INTO divisas VALUES('BHD','48','Dinar bareiní','Bahraini dinar')");
        db.execSQL("INSERT INTO divisas VALUES('BIF','108','Franco de Burundi','Burundian franc')");
        db.execSQL("INSERT INTO divisas VALUES('BMD','60','Dólar bermudeño','Bermudian dollar')");
        db.execSQL("INSERT INTO divisas VALUES('BND','96','Dólar de Brunéi','Brunei dollar')");
        db.execSQL("INSERT INTO divisas VALUES('BOB','68','Boliviano','Boliviano')");
        db.execSQL("INSERT INTO divisas VALUES('BOV','984','MVDOL','Bolivian Mvdol (funds code)')");
        db.execSQL("INSERT INTO divisas VALUES('BRL','986','Real brasileño','Brazilian real')");
        db.execSQL("INSERT INTO divisas VALUES('BSD','44','Dólar bahameño','Bahamian dollar')");
        db.execSQL("INSERT INTO divisas VALUES('BTN','64','Ngultrum','Bhutanese ngultrum')");
        db.execSQL("INSERT INTO divisas VALUES('BWP','72','Pula','Botswana pula')");
        db.execSQL("INSERT INTO divisas VALUES('BYR','974','Rublo bielorruso','Belarusian ruble')");
        db.execSQL("INSERT INTO divisas VALUES('BZD','84','Dólar beliceño','Belize dollar')");
        db.execSQL("INSERT INTO divisas VALUES('CAD','124','Dólar canadiense','Canadian dollar')");
        db.execSQL("INSERT INTO divisas VALUES('CDF','976','Franco congoleño','Congolese franc')");
        db.execSQL("INSERT INTO divisas VALUES('CHE','947','Euro WIR','WIR Euro (complementary currency)')");
        db.execSQL("INSERT INTO divisas VALUES('CHF','756','Franco suizo','Swiss franc')");
        db.execSQL("INSERT INTO divisas VALUES('CHW','948','Franco WIR','WIR Franc (complementary currency)')");
        db.execSQL("INSERT INTO divisas VALUES('CLF','990','Unidad de fomento','Unidad de Fomento (funds code)')");
        db.execSQL("INSERT INTO divisas VALUES('CLP','152','Peso chileno','Chilean peso')");
        db.execSQL("INSERT INTO divisas VALUES('CNY','156','Yuan chino','Chinese yuan')");
        db.execSQL("INSERT INTO divisas VALUES('COP','170','Peso colombiano','Colombian peso')");
        db.execSQL("INSERT INTO divisas VALUES('COU','970','Unidad de valor real','Unidad de Valor Real (UVR) (funds code)[7]')");
        db.execSQL("INSERT INTO divisas VALUES('CRC','188','Colón costarricense','Costa Rican colon')");
        db.execSQL("INSERT INTO divisas VALUES('CUC','931','Peso convertible','Cuban convertible peso')");
        db.execSQL("INSERT INTO divisas VALUES('CUP','192','Peso cubano','Cuban peso')");
        db.execSQL("INSERT INTO divisas VALUES('CVE','132','Escudo caboverdiano','Cape Verde escudo')");
        db.execSQL("INSERT INTO divisas VALUES('CZK','203','Corona checa','Czech koruna')");
        db.execSQL("INSERT INTO divisas VALUES('DJF','262','Franco yibutiano','Djiboutian franc')");
        db.execSQL("INSERT INTO divisas VALUES('DKK','208','Corona danesa','Danish krone')");
        db.execSQL("INSERT INTO divisas VALUES('DOP','214','Peso dominicano','Dominican peso')");
        db.execSQL("INSERT INTO divisas VALUES('DZD','12','Dinar argelino','Algerian dinar')");
        db.execSQL("INSERT INTO divisas VALUES('EGP','818','Libra egipcia','Egyptian pound')");
        db.execSQL("INSERT INTO divisas VALUES('ERN','232','Nakfa','Eritrean nakfa')");
        db.execSQL("INSERT INTO divisas VALUES('ETB','230','Birr etíope','Ethiopian birr')");
        db.execSQL("INSERT INTO divisas VALUES('EUR','978','Euro','Euro')");
        db.execSQL("INSERT INTO divisas VALUES('FJD','242','Dólar fiyiano','Fiji dollar')");
        db.execSQL("INSERT INTO divisas VALUES('FKP','238','Libra malvinense','Falkland Islands pound')");
        db.execSQL("INSERT INTO divisas VALUES('GBP','826','Libra esterlina','Pound sterling')");
        db.execSQL("INSERT INTO divisas VALUES('GEL','981','Lari','Georgian lari')");
        db.execSQL("INSERT INTO divisas VALUES('GHS','936','Cedi ghanés','Ghanaian cedi')");
        db.execSQL("INSERT INTO divisas VALUES('GIP','292','Libra de Gibraltar','Gibraltar pound')");
        db.execSQL("INSERT INTO divisas VALUES('GMD','270','Dalasi','Gambian dalasi')");
        db.execSQL("INSERT INTO divisas VALUES('GNF','324','Franco guineano','Guinean franc')");
        db.execSQL("INSERT INTO divisas VALUES('GTQ','320','Quetzal','Guatemalan quetzal')");
        db.execSQL("INSERT INTO divisas VALUES('GYD','328','Dólar guyanés','Guyanese dollar')");
        db.execSQL("INSERT INTO divisas VALUES('HKD','344','Dólar de Hong Kong','Hong Kong dollar')");
        db.execSQL("INSERT INTO divisas VALUES('HNL','340','Lempira','Honduran lempira')");
        db.execSQL("INSERT INTO divisas VALUES('HRK','191','Kuna','Croatian kuna')");
        db.execSQL("INSERT INTO divisas VALUES('HTG','332','Gourde','Haitian gourde')");
        db.execSQL("INSERT INTO divisas VALUES('HUF','348','Forinto','Hungarian forint')");
        db.execSQL("INSERT INTO divisas VALUES('IDR','360','Rupia indonesia','Indonesian rupiah')");
        db.execSQL("INSERT INTO divisas VALUES('ILS','376','Nuevo shéquel israelí','Israeli new shekel')");
        db.execSQL("INSERT INTO divisas VALUES('INR','356','Rupia india','Indian rupee')");
        db.execSQL("INSERT INTO divisas VALUES('IQD','368','Dinar iraquí','Iraqi dinar')");
        db.execSQL("INSERT INTO divisas VALUES('IRR','364','Rial iraní','Iranian rial')");
        db.execSQL("INSERT INTO divisas VALUES('ISK','352','Corona islandesa','Icelandic króna')");
        db.execSQL("INSERT INTO divisas VALUES('JMD','388','Dólar jamaiquino','Jamaican dollar')");
        db.execSQL("INSERT INTO divisas VALUES('JOD','400','Dinar jordano','Jordanian dinar')");
        db.execSQL("INSERT INTO divisas VALUES('JPY','392','Yen','Japanese yen')");
        db.execSQL("INSERT INTO divisas VALUES('KES','404','Chelín keniano','Kenyan shilling')");
        db.execSQL("INSERT INTO divisas VALUES('KGS','417','Som','Kyrgyzstani som')");
        db.execSQL("INSERT INTO divisas VALUES('KHR','116','Riel','Cambodian riel')");
        db.execSQL("INSERT INTO divisas VALUES('KMF','174','Franco comorense','Comoro franc')");
        db.execSQL("INSERT INTO divisas VALUES('KPW','408','Won norcoreano','North Korean won')");
        db.execSQL("INSERT INTO divisas VALUES('KRW','410','Won','South Korean won')");
        db.execSQL("INSERT INTO divisas VALUES('KWD','414','Dinar kuwaití','Kuwaiti dinar')");
        db.execSQL("INSERT INTO divisas VALUES('KYD','136','Dólar de las Islas Caimán','Cayman Islands dollar')");
        db.execSQL("INSERT INTO divisas VALUES('KZT','398','Tenge','Kazakhstani tenge')");
        db.execSQL("INSERT INTO divisas VALUES('LAK','418','Kip','Lao kip')");
        db.execSQL("INSERT INTO divisas VALUES('LBP','422','Libra libanesa','Lebanese pound')");
        db.execSQL("INSERT INTO divisas VALUES('LKR','144','Rupia de Sri Lanka','Sri Lankan rupee')");
        db.execSQL("INSERT INTO divisas VALUES('LRD','430','Dólar liberiano','Liberian dollar')");
        db.execSQL("INSERT INTO divisas VALUES('LSL','426','Loti','Lesotho loti')");
        db.execSQL("INSERT INTO divisas VALUES('LYD','434','Dinar libio','Libyan dinar')");
        db.execSQL("INSERT INTO divisas VALUES('MAD','504','Dírham marroquí','Moroccan dirham')");
        db.execSQL("INSERT INTO divisas VALUES('MDL','498','Leu moldavo','Moldovan leu')");
        db.execSQL("INSERT INTO divisas VALUES('MGA','969','Ariary malgache','Malagasy ariary')");
        db.execSQL("INSERT INTO divisas VALUES('MKD','807','Denar','Macedonian denar')");
        db.execSQL("INSERT INTO divisas VALUES('MMK','104','Kyat','Myanmar kyat')");
        db.execSQL("INSERT INTO divisas VALUES('MNT','496','Tugrik','Mongolian tögrög')");
        db.execSQL("INSERT INTO divisas VALUES('MOP','446','Pataca','Macanese pataca')");
        db.execSQL("INSERT INTO divisas VALUES('MRO','478','Uguiya','Mauritanian ouguiya')");
        db.execSQL("INSERT INTO divisas VALUES('MUR','480','Rupia de Mauricio','Mauritian rupee')");
        db.execSQL("INSERT INTO divisas VALUES('MVR','462','Rufiyaa','Maldivian rufiyaa')");
        db.execSQL("INSERT INTO divisas VALUES('MWK','454','Kwacha','Malawian kwacha')");
        db.execSQL("INSERT INTO divisas VALUES('MXN','484','Peso mexicano','Mexican peso')");
        db.execSQL("INSERT INTO divisas VALUES('MXV','979','Unidad de Inversión (UDI) mexicana','Mexican Unidad de Inversion (UDI) (funds code)')");
        db.execSQL("INSERT INTO divisas VALUES('MYR','458','Ringgit malayo','Malaysian ringgit')");
        db.execSQL("INSERT INTO divisas VALUES('MZN','943','Metical mozambiqueño','Mozambican metical')");
        db.execSQL("INSERT INTO divisas VALUES('NAD','516','Dólar namibio','Namibian dollar')");
        db.execSQL("INSERT INTO divisas VALUES('NGN','566','Naira','Nigerian naira')");
        db.execSQL("INSERT INTO divisas VALUES('NIO','558','Córdoba','Nicaraguan córdoba')");
        db.execSQL("INSERT INTO divisas VALUES('NOK','578','Corona noruega','Norwegian krone')");
        db.execSQL("INSERT INTO divisas VALUES('NPR','524','Rupia nepalí','Nepalese rupee')");
        db.execSQL("INSERT INTO divisas VALUES('NZD','554','Dólar neozelandés','New Zealand dollar')");
        db.execSQL("INSERT INTO divisas VALUES('OMR','512','Rial omaní','Omani rial')");
        db.execSQL("INSERT INTO divisas VALUES('PAB','590','Balboa','Panamanian balboa')");
        db.execSQL("INSERT INTO divisas VALUES('PEN','604','Sol','Peruvian Sol')");
        db.execSQL("INSERT INTO divisas VALUES('PGK','598','Kina','Papua New Guinean kina')");
        db.execSQL("INSERT INTO divisas VALUES('PHP','608','Peso filipino','Philippine peso')");
        db.execSQL("INSERT INTO divisas VALUES('PKR','586','Rupia pakistaní','Pakistani rupee')");
        db.execSQL("INSERT INTO divisas VALUES('PLN','985','Złoty','Polish złoty')");
        db.execSQL("INSERT INTO divisas VALUES('PYG','600','Guaraní','Paraguayan guaraní')");
        db.execSQL("INSERT INTO divisas VALUES('QAR','634','Riyal qatarí','Qatari riyal')");
        db.execSQL("INSERT INTO divisas VALUES('RON','946','Leu rumano','Romanian leu')");
        db.execSQL("INSERT INTO divisas VALUES('RSD','941','Dinar serbio','Serbian dinar')");
        db.execSQL("INSERT INTO divisas VALUES('RUB','643','Rublo ruso','Russian ruble')");
        db.execSQL("INSERT INTO divisas VALUES('RWF','646','Franco ruandés','Rwandan franc')");
        db.execSQL("INSERT INTO divisas VALUES('SAR','682','Riyal saudí','Saudi riyal')");
        db.execSQL("INSERT INTO divisas VALUES('SBD','90','Dólar de las Islas Salomón','Solomon Islands dollar')");
        db.execSQL("INSERT INTO divisas VALUES('SCR','690','Rupia seychelense','Seychelles rupee')");
        db.execSQL("INSERT INTO divisas VALUES('SDG','938','Dinar sudanés','Sudanese pound')");
        db.execSQL("INSERT INTO divisas VALUES('SEK','752','Corona sueca','Swedish krona/kronor')");
        db.execSQL("INSERT INTO divisas VALUES('SGD','702','Dólar de Singapur','Singapore dollar')");
        db.execSQL("INSERT INTO divisas VALUES('SHP','654','Libra de Santa Elena','Saint Helena pound')");
        db.execSQL("INSERT INTO divisas VALUES('SLL','694','Leone','Sierra Leonean leone')");
        db.execSQL("INSERT INTO divisas VALUES('SOS','706','Chelín somalí','Somali shilling')");
        db.execSQL("INSERT INTO divisas VALUES('SRD','968','Dólar surinamés','Surinamese dollar')");
        db.execSQL("INSERT INTO divisas VALUES('SSP','728','Libra sursudanesa','South Sudanese pound')");
        db.execSQL("INSERT INTO divisas VALUES('STD','678','Dobra','São Tomé and Príncipe dobra')");
        db.execSQL("INSERT INTO divisas VALUES('SVC','222','Colon Salvadoreño','Salvadoran colón')");
        db.execSQL("INSERT INTO divisas VALUES('SYP','760','Libra siria','Syrian pound')");
        db.execSQL("INSERT INTO divisas VALUES('SZL','748','Lilangeni','Swazi lilangeni')");
        db.execSQL("INSERT INTO divisas VALUES('THB','764','Baht','Thai baht')");
        db.execSQL("INSERT INTO divisas VALUES('TJS','972','Somoni tayiko','Tajikistani somoni')");
        db.execSQL("INSERT INTO divisas VALUES('TMT','934','Manat turcomano','Turkmenistani manat')");
        db.execSQL("INSERT INTO divisas VALUES('TND','788','Dinar tunecino','Tunisian dinar')");
        db.execSQL("INSERT INTO divisas VALUES('TOP','776','Paʻanga','Tongan paʻanga')");
        db.execSQL("INSERT INTO divisas VALUES('TRY','949','Lira turca','Turkish lira')");
        db.execSQL("INSERT INTO divisas VALUES('TTD','780','Dólar de Trinidad y Tobago','Trinidad and Tobago dollar')");
        db.execSQL("INSERT INTO divisas VALUES('TWD','901','Nuevo dólar taiwanés','New Taiwan dollar')");
        db.execSQL("INSERT INTO divisas VALUES('TZS','834','Chelín tanzano','Tanzanian shilling')");
        db.execSQL("INSERT INTO divisas VALUES('UAH','980','Grivna','Ukrainian hryvnia')");
        db.execSQL("INSERT INTO divisas VALUES('UGX','800','Chelín ugandés','Ugandan shilling')");
        db.execSQL("INSERT INTO divisas VALUES('USD','840','Dólar estadounidense','United States dollar')");
        db.execSQL("INSERT INTO divisas VALUES('USN','997','Dólar estadounidense (Siguiente día)','United States dollar (next day) (funds code)')");
        db.execSQL("INSERT INTO divisas VALUES('UYI','940','Peso en Unidades Indexadas (Uruguay)','Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)')");
        db.execSQL("INSERT INTO divisas VALUES('UYU','858','Peso uruguayo','Uruguayan peso')");
        db.execSQL("INSERT INTO divisas VALUES('UZS','860','Som uzbeko','Uzbekistan som')");
        db.execSQL("INSERT INTO divisas VALUES('VEF','937','Bolívar','Venezuelan bolívar')");
        db.execSQL("INSERT INTO divisas VALUES('VND','704','Dong vietnamita','Vietnamese dong')");
        db.execSQL("INSERT INTO divisas VALUES('VUV','548','Vatu','Vanuatu vatu')");
        db.execSQL("INSERT INTO divisas VALUES('WST','882','Tala','Samoan tala')");
        db.execSQL("INSERT INTO divisas VALUES('XAF','950','Franco CFA de África Central','CFA franc BEAC')");
        db.execSQL("INSERT INTO divisas VALUES('XAG','961','Plata (una onza troy)','Silver (one troy ounce)')");
        db.execSQL("INSERT INTO divisas VALUES('XAU','959','Oro (una onza troy)','Gold (one troy ounce)')");
        db.execSQL("INSERT INTO divisas VALUES('XBA','955','Unidad compuesta europea (EURCO) (Unidad del mercados de bonos)','European Composite Unit (EURCO) (bond market unit)')");
        db.execSQL("INSERT INTO divisas VALUES('XBB','956','Unidad Monetaria europea (E.M.U.-6) (Unidad del mercado de bonos)','European Monetary Unit (E.M.U.-6) (bond market unit)')");
        db.execSQL("INSERT INTO divisas VALUES('XBC','957','Unidad europea de cuenta 9 (E.U.A.-9) (Unidad del mercado de bonos)','European Unit of Account 9 (E.U.A.-9) (bond market unit)')");
        db.execSQL("INSERT INTO divisas VALUES('XBD','958','Unidad europea de cuenta 17 (E.U.A.-17) (Unidad del mercado de bonos)','European Unit of Account 17 (E.U.A.-17) (bond market unit)')");
        db.execSQL("INSERT INTO divisas VALUES('XCD','951','Dólar del Caribe Oriental','East Caribbean dollar')");
        db.execSQL("INSERT INTO divisas VALUES('XDR','960','Derechos especiales de giro','Special drawing rights')");
        db.execSQL("INSERT INTO divisas VALUES('XOF','952','Franco CFA de África Occidental','CFA franc BCEAO')");
        db.execSQL("INSERT INTO divisas VALUES('XPD','964','Paladio (una onza troy)','Palladium (one troy ounce)')");
        db.execSQL("INSERT INTO divisas VALUES('XPF','953','Franco CFP','CFP franc (franc Pacifique)')");
        db.execSQL("INSERT INTO divisas VALUES('XPT','962','Platino (una onza troy)','Platinum (one troy ounce)')");
        db.execSQL("INSERT INTO divisas VALUES('XSU','994','SUCRE','SUCRE')");
        db.execSQL("INSERT INTO divisas VALUES('XTS','963','Reservado para pruebas','Code reserved for testing purposes')");
        db.execSQL("INSERT INTO divisas VALUES('XUA','965','Unidad de cuenta BAD','ADB Unit of Account')");
        db.execSQL("INSERT INTO divisas VALUES('YER','886','Rial yemení','Yemeni rial')");
        db.execSQL("INSERT INTO divisas VALUES('ZAR','710','Rand','South African rand')");
        db.execSQL("INSERT INTO divisas VALUES('ZMW','967','Kwacha zambiano','Zambian kwacha')");
        db.execSQL("INSERT INTO divisas VALUES('ZWL','932','Dólar zimbabuense','Zimbabwean dollar A/10')");
        db.execSQL("INSERT INTO divisas VALUES('XXX',NULL,'Sin divisa','No currency ')");

        db.execSQL("DROP TABLE IF EXISTS paises");
        db.execSQL("CREATE TABLE paises (ID_PAIS  PRIMARY KEY  NOT NULL  UNIQUE , ID_PAIS_2 , PAIS_EN , PAIS_ES , DIVISAS , HIMNO , ICON , URL_ES , URL_EN )");
        db.execSQL("INSERT INTO paises VALUES('AF','AFG','Afghanistan','Afganistán','AFN','https://upload.wikimedia.org/wikipedia/commons/b/bd/National_Anthem_of_the_Islamic_Republic_of_Afghanistan.ogg','AFG.svg','https://es.wikipedia.org/wiki/Afganist%C3%A1n','https://en.wikipedia.org/wiki/Afghanistan')");
        db.execSQL("INSERT INTO paises VALUES('AX','ALA','Åland Islands','Åland','EUR',NULL,'ALA.svg','https://es.wikipedia.org/wiki/%C3%85land','https://en.wikipedia.org/wiki/%C3%85land_Islands')");
        db.execSQL("INSERT INTO paises VALUES('AL','ALB','Albania','Albania','ALL','https://upload.wikimedia.org/wikipedia/commons/5/52/Hymni_i_Flamurit_instrumental.ogg','ALB.svg','https://es.wikipedia.org/wiki/Albania','https://en.wikipedia.org/wiki/Albania')");
        db.execSQL("INSERT INTO paises VALUES('DZ','DZA','Algeria','Argelia','DZD','https://upload.wikimedia.org/wikipedia/commons/7/79/National_anthem_of_Algeria%2C_by_the_U.S._Navy_Band.oga','DZA.svg','https://es.wikipedia.org/wiki/Argelia','https://en.wikipedia.org/wiki/Algeria')");
        db.execSQL("INSERT INTO paises VALUES('AS','ASM','American Samoa','Samoa Americana','USD',NULL,'ASM.svg','https://es.wikipedia.org/wiki/Samoa_Americana','https://en.wikipedia.org/wiki/American_Samoa')");
        db.execSQL("INSERT INTO paises VALUES('AD','AND','Andorra','Andorra','EUR',NULL,'AND.svg','https://es.wikipedia.org/wiki/Andorra','https://en.wikipedia.org/wiki/Andorra')");
        db.execSQL("INSERT INTO paises VALUES('AO','AGO','Angola','Angola','AOA',NULL,'AGO.svg','https://es.wikipedia.org/wiki/Angola','https://en.wikipedia.org/wiki/Angola')");
        db.execSQL("INSERT INTO paises VALUES('AI','AIA','Anguilla','Anguila','XCD',NULL,'AIA.svg','https://es.wikipedia.org/wiki/Anguila_(dependencia)','https://en.wikipedia.org/wiki/Anguilla')");
        db.execSQL("INSERT INTO paises VALUES('AQ','ATA','Antarctica','Antártida','XXX',NULL,'ATA.svg','https://es.wikipedia.org/wiki/Ant%C3%A1rtida','https://en.wikipedia.org/wiki/Antarctica')");
        db.execSQL("INSERT INTO paises VALUES('AG','ATG','Antigua and Barbuda','Antigua y Barbuda','XCD','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','ATG.svg','https://es.wikipedia.org/wiki/Antigua_y_Barbuda','https://en.wikipedia.org/wiki/Antigua_and_Barbuda')");
        db.execSQL("INSERT INTO paises VALUES('AR','ARG','Argentina','Argentina','ARS','https://upload.wikimedia.org/wikipedia/commons/c/cd/Himno_Nacional_Argentino_instrumental.ogg','ARG.svg','https://es.wikipedia.org/wiki/Argentina','https://en.wikipedia.org/wiki/Argentina')");
        db.execSQL("INSERT INTO paises VALUES('AM','ARM','Armenia','Armenia','AMD','https://upload.wikimedia.org/wikipedia/commons/c/c7/Mer_Hayrenik_instrumental.ogg','ARM.svg','https://es.wikipedia.org/wiki/Armenia','https://en.wikipedia.org/wiki/Armenia')");
        db.execSQL("INSERT INTO paises VALUES('AW','ABW','Aruba','Aruba','AWG','https://upload.wikimedia.org/wikipedia/commons/9/92/Aruba_Dushi_Tera_instrumental.ogg','ABW.svg','https://es.wikipedia.org/wiki/Aruba','https://en.wikipedia.org/wiki/Aruba')");
        db.execSQL("INSERT INTO paises VALUES('AU','AUS','Australia','Australia','AUD','https://upload.wikimedia.org/wikipedia/commons/a/a6/U.S._Navy_Band%2C_Advance_Australia_Fair_%28instrumental%29.ogg','AUS.svg','https://es.wikipedia.org/wiki/Australia','https://en.wikipedia.org/wiki/Australia')");
        db.execSQL("INSERT INTO paises VALUES('AT','AUT','Austria','Austria','EUR','https://upload.wikimedia.org/wikipedia/commons/7/7c/Land_der_Berge_Land_am_Strome_instrumental.ogg','AUT.svg','https://es.wikipedia.org/wiki/Austria','https://en.wikipedia.org/wiki/Austria')");
        db.execSQL("INSERT INTO paises VALUES('AZ','AZE','Azerbaijan','Azerbaiyán','AZN','https://upload.wikimedia.org/wikipedia/commons/3/31/Azerbaijan_national_anthem_%28vocal_version%29.ogg','AZE.svg','https://es.wikipedia.org/wiki/Azerbaiy%C3%A1n','https://en.wikipedia.org/wiki/Azerbaijan')");
        db.execSQL("INSERT INTO paises VALUES('BS','BHS','Bahamas','Bahamas','BSD','https://upload.wikimedia.org/wikipedia/commons/e/e2/National_Anthem_of_Bahamas.ogg','BHS.svg','https://es.wikipedia.org/wiki/Bahamas','https://en.wikipedia.org/wiki/Bahamas')");
        db.execSQL("INSERT INTO paises VALUES('BH','BHR','Bahrain','Baréin','BHD','https://upload.wikimedia.org/wikipedia/commons/2/21/Bahraini_Anthem.ogg','BHR.svg','https://es.wikipedia.org/wiki/Bar%C3%A9in','https://en.wikipedia.org/wiki/Bahrain')");
        db.execSQL("INSERT INTO paises VALUES('BD','BGD','Bangladesh','Bangladés','BDT','https://upload.wikimedia.org/wikipedia/commons/3/3b/Amar_Shonar_Bangla_instrumental.ogg','BGD.svg','https://es.wikipedia.org/wiki/Banglad%C3%A9s','https://en.wikipedia.org/wiki/Bangladesh')");
        db.execSQL("INSERT INTO paises VALUES('BB','BRB','Barbados','Barbados','BBD','https://upload.wikimedia.org/wikipedia/commons/7/73/In_Plenty_and_In_Time_of_Need_instrumental.ogg','BRB.svg','https://es.wikipedia.org/wiki/Barbados','https://en.wikipedia.org/wiki/Barbados')");
        db.execSQL("INSERT INTO paises VALUES('BY','BLR','Belarus','Bielorrusia','BYR','https://upload.wikimedia.org/wikipedia/commons/3/35/My_Belarusy_vocal.ogg','BLR.svg','https://es.wikipedia.org/wiki/Bielorrusia','https://en.wikipedia.org/wiki/Belarus')");
        db.execSQL("INSERT INTO paises VALUES('BE','BEL','Belgium','Bélgica','EUR','https://upload.wikimedia.org/wikipedia/commons/c/c0/The_Brabanconne.ogg','BEL.svg','https://es.wikipedia.org/wiki/B%C3%A9lgica','https://en.wikipedia.org/wiki/Belgium')");
        db.execSQL("INSERT INTO paises VALUES('BZ','BLZ','Belize','Belice','BZD','https://en.wikipedia.org/wiki/File:Land_of_the_Free_instrumental.ogg','BLZ.svg','https://es.wikipedia.org/wiki/Belice','https://en.wikipedia.org/wiki/Belize')");
        db.execSQL("INSERT INTO paises VALUES('BJ','BEN','Benin','Benín','XOF','https://en.wikipedia.org/wiki/File:L%27Aube_Nouvelle.ogg','BEN.svg','https://es.wikipedia.org/wiki/Ben%C3%ADn','https://en.wikipedia.org/wiki/Benin')");
        db.execSQL("INSERT INTO paises VALUES('BM','BMU','Bermuda','Bermudas','BMD','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','BMU.svg','https://es.wikipedia.org/wiki/Bermudas','https://en.wikipedia.org/wiki/Bermuda')");
        db.execSQL("INSERT INTO paises VALUES('BT','BTN','Bhutan','Bután','BTN-INR',NULL,'BTN.svg','https://es.wikipedia.org/wiki/But%C3%A1n','https://en.wikipedia.org/wiki/Bhutan')");
        db.execSQL("INSERT INTO paises VALUES('BO','BOL','Bolivia (Plurinational State of)','Bolivia','BOB-BOV','https://upload.wikimedia.org/wikipedia/commons/5/54/Himno_Nacional_de_Bolivia_instrumental.ogg','BOL.svg','https://es.wikipedia.org/wiki/Bolivia','https://en.wikipedia.org/wiki/Bolivia_(Plurinational_State_of)')");
        db.execSQL("INSERT INTO paises VALUES('BQ','BES','Bonaire, Sint Eustatius and Saba','Bonaire, San Eustaquio y Saba',NULL,NULL,'BES.svg','https://es.wikipedia.org/wiki/Caribe_Neerland%C3%A9s','https://en.wikipedia.org/wiki/Bonaire,_Sint_Eustatius_and_Saba')");
        db.execSQL("INSERT INTO paises VALUES('BA','BIH','Bosnia and Herzegovina','Bosnia y Herzegovina','BAM','https://upload.wikimedia.org/wikipedia/en/5/53/Bosnia_and_Herzegovina_anthem.ogg','BIH.svg','https://es.wikipedia.org/wiki/Bosnia_y_Herzegovina','https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina')");
        db.execSQL("INSERT INTO paises VALUES('BW','BWA','Botswana','Botsuana','BWP','https://upload.wikimedia.org/wikipedia/commons/c/cb/United_States_Navy_Band_-_Fatshe_leno_la_rona.ogg','BWA.svg','https://es.wikipedia.org/wiki/Botsuana','https://en.wikipedia.org/wiki/Botswana')");
        db.execSQL("INSERT INTO paises VALUES('BV','BVT','Bouvet Island','Isla Bouvet','NOK',NULL,'BVT.svg','https://es.wikipedia.org/wiki/Isla_Bouvet','https://en.wikipedia.org/wiki/Bouvet_Island')");
        db.execSQL("INSERT INTO paises VALUES('BR','BRA','Brazil','Brasil','BRL','https://upload.wikimedia.org/wikipedia/commons/0/0d/Hino-Nacional-Brasil-instrumental-mec.ogg','BRA.svg','https://es.wikipedia.org/wiki/Brasil','https://en.wikipedia.org/wiki/Brazil')");
        db.execSQL("INSERT INTO paises VALUES('IO','IOT','British Indian Ocean Territory','Territorio Británico del Océano Índico','USD','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','IOT.svg','https://es.wikipedia.org/wiki/Territorio_Brit%C3%A1nico_del_Oc%C3%A9ano_%C3%8Dndico','https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory')");
        db.execSQL("INSERT INTO paises VALUES('BN','BRN','Brunei Darussalam','Brunéi','BND','https://upload.wikimedia.org/wikipedia/commons/b/b2/United_States_Navy_Band_-_Allah_Peliharakan_Sultan.oga','BRN.svg','https://es.wikipedia.org/wiki/Brun%C3%A9i','https://en.wikipedia.org/wiki/Brunei_Darussalam')");
        db.execSQL("INSERT INTO paises VALUES('BG','BGR','Bulgaria','Bulgaria','BGN','https://upload.wikimedia.org/wikipedia/commons/9/9c/Mila_Rodino.ogg','BGR.svg','https://es.wikipedia.org/wiki/Bulgaria','https://en.wikipedia.org/wiki/Bulgaria')");
        db.execSQL("INSERT INTO paises VALUES('BF','BFA','Burkina Faso','Burkina Faso','XOF','https://upload.wikimedia.org/wikipedia/commons/7/7e/Hymne_National_du_Burkina_Faso.ogg','BFA.svg','https://es.wikipedia.org/wiki/Burkina_Faso','https://en.wikipedia.org/wiki/Burkina_Faso')");
        db.execSQL("INSERT INTO paises VALUES('BI','BDI','Burundi','Burundi','BIF',NULL,'BDI.svg','https://es.wikipedia.org/wiki/Burundi','https://en.wikipedia.org/wiki/Burundi')");
        db.execSQL("INSERT INTO paises VALUES('CV','CPV','Cabo Verde','Cabo Verde','CVE','https://upload.wikimedia.org/wikipedia/commons/e/e1/National_Anthem_of_Cap_Verde_by_US_Navy_Band.ogg','CPV.svg','https://es.wikipedia.org/wiki/Cabo_Verde','https://en.wikipedia.org/wiki/Cabo_Verde')");
        db.execSQL("INSERT INTO paises VALUES('KH','KHM','Cambodia','Camboya','KHR','https://upload.wikimedia.org/wikipedia/commons/a/af/United_States_Navy_Band_-_Nokoreach.ogg','KHM.svg','https://es.wikipedia.org/wiki/Camboya','https://en.wikipedia.org/wiki/Cambodia')");
        db.execSQL("INSERT INTO paises VALUES('CM','CMR','Cameroon','Camerún','XAF','https://upload.wikimedia.org/wikipedia/commons/c/cc/United_States_Navy_Band_-_Chant_de_Ralliement.ogg','CMR.svg','https://es.wikipedia.org/wiki/Camer%C3%BAn','https://en.wikipedia.org/wiki/Cameroon')");
        db.execSQL("INSERT INTO paises VALUES('CA','CAN','Canada','Canadá','CAD','https://upload.wikimedia.org/wikipedia/commons/9/9e/O_Canada.ogg','CAN.svg','https://es.wikipedia.org/wiki/Canad%C3%A1','https://en.wikipedia.org/wiki/Canada')");
        db.execSQL("INSERT INTO paises VALUES('KY','CYM','Cayman Islands','Islas Caimán','KYD','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','CYM.svg','https://es.wikipedia.org/wiki/Islas_Caim%C3%A1n','https://en.wikipedia.org/wiki/Cayman_Islands')");
        db.execSQL("INSERT INTO paises VALUES('CF','CAF','Central African Republic','República Centroafricana','XAF',NULL,'CAF.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_Centroafricana','https://en.wikipedia.org/wiki/Central_African_Republic')");
        db.execSQL("INSERT INTO paises VALUES('TD','TCD','Chad','Chad','XAF',NULL,'TCD.svg','https://es.wikipedia.org/wiki/Chad','https://en.wikipedia.org/wiki/Chad')");
        db.execSQL("INSERT INTO paises VALUES('CL','CHL','Chile','Chile','CLF-CLP','https://upload.wikimedia.org/wikipedia/commons/6/6e/United_States_Navy_Band_-_National_Anthem_of_Chile.ogg','CHL.svg','https://es.wikipedia.org/wiki/Chile','https://en.wikipedia.org/wiki/Chile')");
        db.execSQL("INSERT INTO paises VALUES('CN','CHN','China','China','CNY-TWD','https://upload.wikimedia.org/wikipedia/commons/b/b9/March_of_the_Volunteers_instrumental.ogg','CHN.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_Popular_China','https://en.wikipedia.org/wiki/China')");
        db.execSQL("INSERT INTO paises VALUES('CX','CXR','Christmas Island','Isla de Navidad','AUD',NULL,'CXR.svg','https://es.wikipedia.org/wiki/Isla_de_Navidad','https://en.wikipedia.org/wiki/Christmas_Island')");
        db.execSQL("INSERT INTO paises VALUES('CC','CCK','Cocos (Keeling) Islands','Islas Cocos','AUD',NULL,'CCK.svg','https://es.wikipedia.org/wiki/Islas_Cocos','https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands')");
        db.execSQL("INSERT INTO paises VALUES('CO','COL','Colombia','Colombia','COP-COU','https://upload.wikimedia.org/wikipedia/commons/5/55/United_States_Navy_Band_-_%C2%A1Oh%2C_gloria_inmarcesible%21.ogg','COL.svg','https://es.wikipedia.org/wiki/Colombia','https://en.wikipedia.org/wiki/Colombia')");
        db.execSQL("INSERT INTO paises VALUES('KM','COM','Comoros','Comoras','KMF','https://upload.wikimedia.org/wikipedia/commons/4/4b/National_Anthem_of_Comoros_by_US_Navy_Band.ogg','COM.svg','https://es.wikipedia.org/wiki/Comoras','https://en.wikipedia.org/wiki/Comoros')");
        db.execSQL("INSERT INTO paises VALUES('CG','COG','Congo, Republic of the','República del Congo','XAF',NULL,'COG.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_del_Congo','https://en.wikipedia.org/wiki/Republic_of_the_Congo')");
        db.execSQL("INSERT INTO paises VALUES('CD','COD','Congo (Democratic Republic of the)','República Democrática del Congo','CDF','https://upload.wikimedia.org/wikipedia/commons/7/70/National_Anthem_of_Democratic_Republic_of_the_Congo_by_US_Navy_Band.ogg','COD.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_Democr%C3%A1tica_del_Congo','https://en.wikipedia.org/wiki/Congo_(Democratic_Republic_of_the)')");
        db.execSQL("INSERT INTO paises VALUES('CK','COK','Cook Islands','Islas Cook','NZD',NULL,'COK.svg','https://es.wikipedia.org/wiki/Islas_Cook','https://en.wikipedia.org/wiki/Cook_Islands')");
        db.execSQL("INSERT INTO paises VALUES('CR','CRI','Costa Rica','Costa Rica','CRC','https://upload.wikimedia.org/wikipedia/commons/7/79/Costa_Rica_National_Anthem.ogg','CRI.svg','https://es.wikipedia.org/wiki/Costa_Rica','https://en.wikipedia.org/wiki/Costa_Rica')");
        db.execSQL("INSERT INTO paises VALUES('CI','CIV','Côte d''Ivoire','Costa de Marfil','XOF','https://upload.wikimedia.org/wikipedia/commons/a/a3/Hymne_National_de_C%C3%B4te_d%27Ivoire.ogg','CIV.svg','https://es.wikipedia.org/wiki/Costa_de_Marfil','https://en.wikipedia.org/wiki/C%C3%B4te_d%27Ivoire')");
        db.execSQL("INSERT INTO paises VALUES('HR','HRV','Croatia','Croacia','HRK','https://upload.wikimedia.org/wikipedia/commons/d/df/Lijepa_nasa_domovino_instrumental.ogg','HRV.svg','https://es.wikipedia.org/wiki/Croacia','https://en.wikipedia.org/wiki/Croatia')");
        db.execSQL("INSERT INTO paises VALUES('CU','CUB','Cuba','Cuba','CUC-CUP','https://upload.wikimedia.org/wikipedia/commons/c/cf/United_States_Navy_Band_-_La_Bayamesa.ogg','CUB.svg','https://es.wikipedia.org/wiki/Cuba','https://en.wikipedia.org/wiki/Cuba')");
        db.execSQL("INSERT INTO paises VALUES('CW','CUW','Curaçao','Curazao','ANG',NULL,'CUW.svg','https://es.wikipedia.org/wiki/Curazao','https://en.wikipedia.org/wiki/Cura%C3%A7ao')");
        db.execSQL("INSERT INTO paises VALUES('CY','CYP','Cyprus','Chipre','EUR','https://upload.wikimedia.org/wikipedia/commons/d/db/Hymn_to_liberty_instrumental.oga','CYP.svg','https://es.wikipedia.org/wiki/Chipre','https://en.wikipedia.org/wiki/Cyprus')");
        db.execSQL("INSERT INTO paises VALUES('CZ','CZE','Czechia','República Checa','CZK','https://upload.wikimedia.org/wikipedia/commons/6/6e/Czech_anthem.ogg','CZE.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_Checa','https://en.wikipedia.org/wiki/Czechia')");
        db.execSQL("INSERT INTO paises VALUES('DK','DNK','Denmark','Dinamarca','DKK','https://upload.wikimedia.org/wikipedia/commons/0/06/United_States_Navy_Band_-_Der_er_et_yndigt_land.ogg','DNK.svg','https://es.wikipedia.org/wiki/Dinamarca','https://en.wikipedia.org/wiki/Denmark')");
        db.execSQL("INSERT INTO paises VALUES('DJ','DJI','Djibouti','Yibuti','DJF','https://upload.wikimedia.org/wikipedia/commons/b/bf/The_Djiboutian_anthem.ogg','DJI.svg','https://es.wikipedia.org/wiki/Yibuti','https://en.wikipedia.org/wiki/Djibouti')");
        db.execSQL("INSERT INTO paises VALUES('DM','DMA','Dominica','Dominica','DOP-XCD','https://upload.wikimedia.org/wikipedia/commons/9/9a/National_Anthem_of_Dominica_by_US_Navy_Band.ogg','DMA.svg','https://es.wikipedia.org/wiki/Dominica','https://en.wikipedia.org/wiki/Dominica')");
        db.execSQL("INSERT INTO paises VALUES('DO','DOM','Dominican Republic','República Dominicana','DOP','https://upload.wikimedia.org/wikipedia/commons/b/bb/Dominican_Republic_National_Anthem.ogg','DOM.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_Dominicana','https://en.wikipedia.org/wiki/Dominican_Republic')");
        db.execSQL("INSERT INTO paises VALUES('EC','ECU','Ecuador','Ecuador','USD','https://upload.wikimedia.org/wikipedia/commons/6/6e/Anthem_of_Ecuador.ogg','ECU.svg','https://es.wikipedia.org/wiki/Ecuador','https://en.wikipedia.org/wiki/Ecuador')");
        db.execSQL("INSERT INTO paises VALUES('EG','EGY','Egypt','Egipto','EGP','https://upload.wikimedia.org/wikipedia/commons/f/f2/Bilady%2C_Bilady%2C_Bilady.ogg','EGY.svg','https://es.wikipedia.org/wiki/Egipto','https://en.wikipedia.org/wiki/Egypt')");
        db.execSQL("INSERT INTO paises VALUES('SV','SLV','El Salvador','El Salvador','SVC-USD','https://upload.wikimedia.org/wikipedia/commons/4/4e/El_Salvador_National_Anthem.ogg','SLV.svg','https://es.wikipedia.org/wiki/El_Salvador','https://en.wikipedia.org/wiki/El_Salvador')");
        db.execSQL("INSERT INTO paises VALUES('GQ','GNQ','Equatorial Guinea','Guinea Ecuatorial','XAF',NULL,'GNQ.svg','https://es.wikipedia.org/wiki/Guinea_Ecuatorial','https://en.wikipedia.org/wiki/Equatorial_Guinea')");
        db.execSQL("INSERT INTO paises VALUES('ER','ERI','Eritrea','Eritrea','ERN','https://upload.wikimedia.org/wikipedia/commons/4/4f/National_Anthem_of_Eritrea_by_US_Navy_Band.ogg','ERI.svg','https://es.wikipedia.org/wiki/Eritrea','https://en.wikipedia.org/wiki/Eritrea')");
        db.execSQL("INSERT INTO paises VALUES('EE','EST','Estonia','Estonia','EUR','https://upload.wikimedia.org/wikipedia/commons/5/52/US_Navy_band_-_National_anthem_of_Estonia.ogg','EST.svg','https://es.wikipedia.org/wiki/Estonia','https://en.wikipedia.org/wiki/Estonia')");
        db.execSQL("INSERT INTO paises VALUES('ET','ETH','Ethiopia','Etiopía','ETB','https://upload.wikimedia.org/wikipedia/commons/8/83/Wedefit_Gesgeshi_Widd_Innat_Ittyoppya.ogg','ETH.svg','https://es.wikipedia.org/wiki/Etiop%C3%ADa','https://en.wikipedia.org/wiki/Ethiopia')");
        db.execSQL("INSERT INTO paises VALUES('FK','FLK','Falkland Islands (Malvinas)','Islas Malvinas','FKP',NULL,'FLK.svg','https://es.wikipedia.org/wiki/Islas_Malvinas_(Territorio_Brit%C3%A1nico_de_Ultramar)','https://en.wikipedia.org/wiki/Falkland_Islands_(Malvinas)')");
        db.execSQL("INSERT INTO paises VALUES('FO','FRO','Faroe Islands','Islas Feroe','DKK',NULL,'FRO.svg','https://es.wikipedia.org/wiki/Islas_Feroe','https://en.wikipedia.org/wiki/Faroe_Islands')");
        db.execSQL("INSERT INTO paises VALUES('FJ','FJI','Fiji','Fiyi','FJD','https://upload.wikimedia.org/wikipedia/commons/c/ca/Fiji_National_Anthem.ogg','FJI.svg','https://es.wikipedia.org/wiki/Fiyi','https://en.wikipedia.org/wiki/Fiji')");
        db.execSQL("INSERT INTO paises VALUES('FI','FIN','Finland','Finlandia','EUR','https://upload.wikimedia.org/wikipedia/commons/6/61/United_States_Navy_Band_-_Maamme.ogg','FIN.svg','https://es.wikipedia.org/wiki/Finlandia','https://en.wikipedia.org/wiki/Finland')");
        db.execSQL("INSERT INTO paises VALUES('FR','FRA','France','Francia','EUR','https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg','FRA.svg','https://es.wikipedia.org/wiki/Francia','https://en.wikipedia.org/wiki/France')");
        db.execSQL("INSERT INTO paises VALUES('GF','GUF','French Guiana','Guayana Francesa','EUR',NULL,'GUF.svg','https://es.wikipedia.org/wiki/Guayana_Francesa','https://en.wikipedia.org/wiki/French_Guiana')");
        db.execSQL("INSERT INTO paises VALUES('PF','PYF','French Polynesia','Polinesia Francesa','XPF','https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg','PYF.svg','https://es.wikipedia.org/wiki/Polinesia_Francesa','https://en.wikipedia.org/wiki/French_Polynesia')");
        db.execSQL("INSERT INTO paises VALUES('TF','ATF','French Southern Territories','Tierras Australes y Antárticas Francesas','EUR','https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg','ATF.svg','https://es.wikipedia.org/wiki/Tierras_Australes_y_Ant%C3%A1rticas_Francesas','https://en.wikipedia.org/wiki/French_Southern_Territories')");
        db.execSQL("INSERT INTO paises VALUES('GA','GAB','Gabon','Gabón','XAF','https://upload.wikimedia.org/wikipedia/commons/f/fc/La_Concorde.ogg','GAB.svg','https://es.wikipedia.org/wiki/Gab%C3%B3n','https://en.wikipedia.org/wiki/Gabon')");
        db.execSQL("INSERT INTO paises VALUES('GM','GMB','Gambia','Gambia','GMD','https://upload.wikimedia.org/wikipedia/commons/2/23/National_Anthem_of_Gambia_by_US_Navy_Band.ogg','GMB.svg','https://es.wikipedia.org/wiki/Gambia','https://en.wikipedia.org/wiki/Gambia')");
        db.execSQL("INSERT INTO paises VALUES('GE','GEO','Georgia','Georgia','GEL-XXX','https://upload.wikimedia.org/wikipedia/commons/e/e3/Tavisupleba_instrumental.ogg','GEO.svg','https://es.wikipedia.org/wiki/Georgia','https://en.wikipedia.org/wiki/Georgia_(country)')");
        db.execSQL("INSERT INTO paises VALUES('DE','DEU','Germany','Alemania','EUR','https://upload.wikimedia.org/wikipedia/commons/c/cb/National_anthem_of_Germany_-_U.S._Army_1st_Armored_Division_Band.ogg','DEU.svg','https://es.wikipedia.org/wiki/Alemania','https://en.wikipedia.org/wiki/Germany')");
        db.execSQL("INSERT INTO paises VALUES('GH','GHA','Ghana','Ghana','GHS','https://upload.wikimedia.org/wikipedia/en/9/95/God_Bless_Our_Homeland_Ghana.ogg','GHA.svg','https://es.wikipedia.org/wiki/Ghana','https://en.wikipedia.org/wiki/Ghana')");
        db.execSQL("INSERT INTO paises VALUES('GI','GIB','Gibraltar','Gibraltar','GIP','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','GIB.svg','https://es.wikipedia.org/wiki/Gibraltar','https://en.wikipedia.org/wiki/Gibraltar')");
        db.execSQL("INSERT INTO paises VALUES('GR','GRC','Greece','Grecia','EUR','https://upload.wikimedia.org/wikipedia/commons/d/db/Hymn_to_liberty_instrumental.oga','GRC.svg','https://es.wikipedia.org/wiki/Grecia','https://en.wikipedia.org/wiki/Greece')");
        db.execSQL("INSERT INTO paises VALUES('GL','GRL','Greenland','Groenlandia','DKK',NULL,'GRL.svg','https://es.wikipedia.org/wiki/Groenlandia','https://en.wikipedia.org/wiki/Greenland')");
        db.execSQL("INSERT INTO paises VALUES('GD','GRD','Grenada','Granada','XCD','https://upload.wikimedia.org/wikipedia/commons/7/76/HailGrenada.ogg','GRD.svg','https://es.wikipedia.org/wiki/Granada_(pa%C3%ADs)','https://en.wikipedia.org/wiki/Grenada')");
        db.execSQL("INSERT INTO paises VALUES('GP','GLP','Guadeloupe','Guadalupe','EUR',NULL,'GLP.svg','https://es.wikipedia.org/wiki/Guadalupe_(Francia)','https://en.wikipedia.org/wiki/Guadeloupe')");
        db.execSQL("INSERT INTO paises VALUES('GU','GUM','Guam','Guam','USD','https://upload.wikimedia.org/wikipedia/commons/8/80/The_Star-Spangled_Banner_-_U.S._Army_1st_Armored_Division_Band.ogg','GUM.svg','https://es.wikipedia.org/wiki/Guam','https://en.wikipedia.org/wiki/Guam')");
        db.execSQL("INSERT INTO paises VALUES('GT','GTM','Guatemala','Guatemala','GTQ','https://upload.wikimedia.org/wikipedia/commons/d/d8/National_Anthem_of_Guatemala_by_US_Navy_Band.ogg','GTM.svg','https://es.wikipedia.org/wiki/Guatemala','https://en.wikipedia.org/wiki/Guatemala')");
        db.execSQL("INSERT INTO paises VALUES('GG','GGY','Guernsey','Guernsey','GBP','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','GGY.svg','https://es.wikipedia.org/wiki/Guernsey','https://en.wikipedia.org/wiki/Guernsey')");
        db.execSQL("INSERT INTO paises VALUES('GN','GIN','Guinea','Guinea','GNF-PGK-XAF-XOF','https://upload.wikimedia.org/wikipedia/commons/6/65/National_Anthem_of_Guinea_by_US_Navy_Band.ogg','GIN.svg','https://es.wikipedia.org/wiki/Guinea','https://en.wikipedia.org/wiki/Guinea')");
        db.execSQL("INSERT INTO paises VALUES('GW','GNB','Guinea-Bissau','Guinea-Bisáu','XOF','https://upload.wikimedia.org/wikipedia/commons/4/40/National_Anthem_of_Guinea-Bissau_by_US_Navy_Band.ogg','GNB.svg','https://es.wikipedia.org/wiki/Guinea-Bis%C3%A1u','https://en.wikipedia.org/wiki/Guinea-Bissau')");
        db.execSQL("INSERT INTO paises VALUES('GY','GUY','Guyana','Guyana','GYD','https://upload.wikimedia.org/wikipedia/commons/8/85/National_Anthem_of_Guyana.ogg','GUY.svg','https://es.wikipedia.org/wiki/Guyana','https://en.wikipedia.org/wiki/Guyana')");
        db.execSQL("INSERT INTO paises VALUES('HT','HTI','Haiti','Haití','HTG-USD','https://upload.wikimedia.org/wikipedia/commons/4/4f/Haiti_National_Anthem.ogg','HTI.svg','https://es.wikipedia.org/wiki/Hait%C3%AD','https://en.wikipedia.org/wiki/Haiti')");
        db.execSQL("INSERT INTO paises VALUES('HM','HMD','Heard Island and McDonald Islands','Islas Heard y McDonald','AUD',NULL,'HMD.svg','https://es.wikipedia.org/wiki/Islas_Heard_y_McDonald','https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands')");
        db.execSQL("INSERT INTO paises VALUES('VA','VAT','Holy See','Vaticano, Ciudad del','EUR','https://upload.wikimedia.org/wikipedia/commons/d/d1/United_States_Navy_Band_-_Inno_e_Marcia_Pontificale.ogg','VAT.svg','https://es.wikipedia.org/wiki/Ciudad_del_Vaticano','https://en.wikipedia.org/wiki/Vatican_City_State')");
        db.execSQL("INSERT INTO paises VALUES('HN','HND','Honduras','Honduras','HNL','https://upload.wikimedia.org/wikipedia/commons/b/b3/Honduras_National_Anthem.ogg','HND.svg','https://es.wikipedia.org/wiki/Honduras','https://en.wikipedia.org/wiki/Honduras')");
        db.execSQL("INSERT INTO paises VALUES('HK','HKG','Hong Kong','Hong Kong','HKD','https://upload.wikimedia.org/wikipedia/commons/b/b9/March_of_the_Volunteers_instrumental.ogg','HKG.svg','https://es.wikipedia.org/wiki/Hong_Kong','https://en.wikipedia.org/wiki/Hong_Kong')");
        db.execSQL("INSERT INTO paises VALUES('HU','HUN','Hungary','Hungría','HUF','https://upload.wikimedia.org/wikipedia/commons/c/c1/Erkel_Ferenc_Magyar_Himnusz.ogg','HUN.svg','https://es.wikipedia.org/wiki/Hungr%C3%ADa','https://en.wikipedia.org/wiki/Hungary')");
        db.execSQL("INSERT INTO paises VALUES('IS','ISL','Iceland','Islandia','ISK','https://upload.wikimedia.org/wikipedia/commons/4/4b/Lofs%C3%B6ngur.ogg','ISL.svg','https://es.wikipedia.org/wiki/Islandia','https://en.wikipedia.org/wiki/Iceland')");
        db.execSQL("INSERT INTO paises VALUES('IN','IND','India','India','INR','https://upload.wikimedia.org/wikipedia/commons/9/94/Jana_Gana_Mana_instrumental.ogg','IND.svg','https://es.wikipedia.org/wiki/India','https://en.wikipedia.org/wiki/India')");
        db.execSQL("INSERT INTO paises VALUES('ID','IDN','Indonesia','Indonesia','IDR','https://upload.wikimedia.org/wikipedia/commons/3/32/Indonesiaraya.ogg','IDN.svg','https://es.wikipedia.org/wiki/Indonesia','https://en.wikipedia.org/wiki/Indonesia')");
        db.execSQL("INSERT INTO paises VALUES('IR','IRN','Iran (Islamic Republic of)','Irán','IRR',NULL,'IRN.svg','https://es.wikipedia.org/wiki/Ir%C3%A1n','https://en.wikipedia.org/wiki/Iran_(Islamic_Republic_of)')");
        db.execSQL("INSERT INTO paises VALUES('IQ','IRQ','Iraq','Irak','IQD','https://upload.wikimedia.org/wikipedia/commons/1/16/United_States_Navy_Band_-_Mawtini.ogg','IRQ.svg','https://es.wikipedia.org/wiki/Irak','https://en.wikipedia.org/wiki/Iraq')");
        db.execSQL("INSERT INTO paises VALUES('IE','IRL','Ireland','Irlanda','EUR','https://upload.wikimedia.org/wikipedia/commons/7/7c/United_States_Navy_Band_-_Amhr%C3%A1n_na_bhFiann.ogg','IRL.svg','https://es.wikipedia.org/wiki/Irlanda','https://en.wikipedia.org/wiki/Republic_of_Ireland')");
        db.execSQL("INSERT INTO paises VALUES('IM','IMN','Isle of Man','Isla de Man','GBP',NULL,'IMN.svg','https://es.wikipedia.org/wiki/Isla_de_Man','https://en.wikipedia.org/wiki/Isle_of_Man')");
        db.execSQL("INSERT INTO paises VALUES('IL','ISR','Israel','Israel','ILS','https://upload.wikimedia.org/wikipedia/commons/2/26/Hatikvah_instrumental.ogg','ISR.svg','https://es.wikipedia.org/wiki/Israel','https://en.wikipedia.org/wiki/Israel')");
        db.execSQL("INSERT INTO paises VALUES('IT','ITA','Italy','Italia','EUR','https://upload.wikimedia.org/wikipedia/commons/c/c0/National_anthem_of_Italy_-_U.S._Navy_Band_%28long_version%29.ogg','ITA.svg','https://es.wikipedia.org/wiki/Italia','https://en.wikipedia.org/wiki/Italy')");
        db.execSQL("INSERT INTO paises VALUES('JM','JAM','Jamaica','Jamaica','JMD','https://upload.wikimedia.org/wikipedia/commons/1/11/Anthems_-_National_Anthem_Of_Jamaica.ogg','JAM.svg','https://es.wikipedia.org/wiki/Jamaica','https://en.wikipedia.org/wiki/Jamaica')");
        db.execSQL("INSERT INTO paises VALUES('JP','JPN','Japan','Japón','JPY','https://upload.wikimedia.org/wikipedia/commons/a/a3/Kimi_ga_Yo_instrumental.ogg','JPN.svg','https://es.wikipedia.org/wiki/Jap%C3%B3n','https://en.wikipedia.org/wiki/Japan')");
        db.execSQL("INSERT INTO paises VALUES('JE','JEY','Jersey','Jersey','GBP','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','JEY.svg','https://es.wikipedia.org/wiki/Jersey','https://en.wikipedia.org/wiki/Jersey')");
        db.execSQL("INSERT INTO paises VALUES('JO','JOR','Jordan','Jordania','JOD','https://upload.wikimedia.org/wikipedia/commons/e/ee/National_anthem_of_Jordan_instrumental.ogg','JOR.svg','https://es.wikipedia.org/wiki/Jordania','https://en.wikipedia.org/wiki/Jordan')");
        db.execSQL("INSERT INTO paises VALUES('KZ','KAZ','Kazakhstan','Kazajistán','KZT','https://upload.wikimedia.org/wikipedia/commons/7/7a/Kazakhstan_national_anthem%2C_played_by_the_U.S._Navy_Band.ogg','KAZ.svg','https://es.wikipedia.org/wiki/Kazajist%C3%A1n','https://en.wikipedia.org/wiki/Kazakhstan')");
        db.execSQL("INSERT INTO paises VALUES('KE','KEN','Kenya','Kenia','KES','https://upload.wikimedia.org/wikipedia/commons/4/49/National_Anthem_of_Kenya.ogg','KEN.svg','https://es.wikipedia.org/wiki/Kenia','https://en.wikipedia.org/wiki/Kenya')");
        db.execSQL("INSERT INTO paises VALUES('KI','KIR','Kiribati','Kiribati','AUD',NULL,'KIR.svg','https://es.wikipedia.org/wiki/Kiribati','https://en.wikipedia.org/wiki/Kiribati')");
        db.execSQL("INSERT INTO paises VALUES('KP','PRK','Korea (Democratic People''s Republic of)','Corea del Norte','KPW','https://upload.wikimedia.org/wikipedia/en/6/65/National_anthem_of_North_Korea.ogg','PRK.svg','https://es.wikipedia.org/wiki/Corea_del_Norte','https://en.wikipedia.org/wiki/North_Korea')");
        db.execSQL("INSERT INTO paises VALUES('KR','KOR','Korea (Republic of)','Corea del Sur','KRW','https://upload.wikimedia.org/wikipedia/commons/0/0c/The_National_Anthem_of_the_Republic_of_Korea.ogg','KOR.svg','https://es.wikipedia.org/wiki/Corea_del_Sur','https://en.wikipedia.org/wiki/Korea_(Republic_of)')");
        db.execSQL("INSERT INTO paises VALUES('KW','KWT','Kuwait','Kuwait','KWD','https://upload.wikimedia.org/wikipedia/commons/c/c4/Kuwait.ogg','KWT.svg','https://es.wikipedia.org/wiki/Kuwait','https://en.wikipedia.org/wiki/Kuwait')");
        db.execSQL("INSERT INTO paises VALUES('KG','KGZ','Kyrgyzstan','Kirguistán','KGS','https://upload.wikimedia.org/wikipedia/commons/b/b5/National_Anthem_of_Kyrgyzstan.ogg','KGZ.svg','https://es.wikipedia.org/wiki/Kirguist%C3%A1n','https://en.wikipedia.org/wiki/Kyrgyzstan')");
        db.execSQL("INSERT INTO paises VALUES('LA','LAO','Lao People''s Democratic Republic','Laos','LAK','https://upload.wikimedia.org/wikipedia/commons/e/ee/National_Anthem_of_Laos.ogg','LAO.svg','https://es.wikipedia.org/wiki/Laos','https://en.wikipedia.org/wiki/Lao_People%27s_Democratic_Republic')");
        db.execSQL("INSERT INTO paises VALUES('LV','LVA','Latvia','Letonia','EUR','https://upload.wikimedia.org/wikipedia/commons/1/12/Latvian_National_Anthem_%28instrumental%29.ogg','LVA.svg','https://es.wikipedia.org/wiki/Letonia','https://en.wikipedia.org/wiki/Latvia')");
        db.execSQL("INSERT INTO paises VALUES('LB','LBN','Lebanon','Líbano','LBP','https://upload.wikimedia.org/wikipedia/commons/9/97/Lebanese_national_anthem.ogg','LBN.svg','https://es.wikipedia.org/wiki/L%C3%ADbano','https://en.wikipedia.org/wiki/Lebanon')");
        db.execSQL("INSERT INTO paises VALUES('LS','LSO','Lesotho','Lesoto','LSL-ZAR',NULL,'LSO.svg','https://es.wikipedia.org/wiki/Lesoto','https://en.wikipedia.org/wiki/Lesotho')");
        db.execSQL("INSERT INTO paises VALUES('LR','LBR','Liberia','Liberia','LRD','https://upload.wikimedia.org/wikipedia/commons/7/7f/All_Hail%2C_Liberia%2C_Hail_%28instrumental%29.oga','LBR.svg','https://es.wikipedia.org/wiki/Liberia','https://en.wikipedia.org/wiki/Liberia')");
        db.execSQL("INSERT INTO paises VALUES('LY','LBY','Libya','Libia','LYD','https://upload.wikimedia.org/wikipedia/commons/9/93/Libya.ogg','LBY.svg','https://es.wikipedia.org/wiki/Libia','https://en.wikipedia.org/wiki/Libya')");
        db.execSQL("INSERT INTO paises VALUES('LI','LIE','Liechtenstein','Liechtenstein','CHF','https://upload.wikimedia.org/wikipedia/commons/6/61/Oben_am_jungen_Rhein%2C_by_the_U.S._Navy_Band.ogg','LIE.svg','https://es.wikipedia.org/wiki/Liechtenstein','https://en.wikipedia.org/wiki/Liechtenstein')");
        db.execSQL("INSERT INTO paises VALUES('LT','LTU','Lithuania','Lituania','EUR','https://upload.wikimedia.org/wikipedia/commons/c/ca/Tauti%C5%A1ka_giesme_instumental.ogg','LTU.svg','https://es.wikipedia.org/wiki/Lituania','https://en.wikipedia.org/wiki/Lithuania')");
        db.execSQL("INSERT INTO paises VALUES('LU','LUX','Luxembourg','Luxemburgo','EUR','https://upload.wikimedia.org/wikipedia/commons/4/45/Luxembourg_National_Anthem.ogg','LUX.svg','https://es.wikipedia.org/wiki/Luxemburgo','https://en.wikipedia.org/wiki/Luxembourg')");
        db.execSQL("INSERT INTO paises VALUES('MO','MAC','Macao','Macao','MOP','https://upload.wikimedia.org/wikipedia/commons/b/b9/March_of_the_Volunteers_instrumental.ogg','MAC.svg','https://es.wikipedia.org/wiki/Macao','https://en.wikipedia.org/wiki/Macao')");
        db.execSQL("INSERT INTO paises VALUES('MK','MKD','Macedonia (the former Yugoslav Republic of)','Macedonia','MKD','https://upload.wikimedia.org/wikipedia/en/3/34/Anthem_of_the_Republic_of_Macedonia_%28Instrumental%29.ogg','MKD.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_de_Macedonia','https://en.wikipedia.org/wiki/Republic_of_Macedonia')");
        db.execSQL("INSERT INTO paises VALUES('MG','MDG','Madagascar','Madagascar','MGA','https://upload.wikimedia.org/wikipedia/commons/d/d3/National_Anthem_of_Madagascar_by_US_Navy_Band.ogg','MDG.svg','https://es.wikipedia.org/wiki/Madagascar','https://en.wikipedia.org/wiki/Madagascar')");
        db.execSQL("INSERT INTO paises VALUES('MW','MWI','Malawi','Malaui','MWK','https://upload.wikimedia.org/wikipedia/commons/c/cb/Malawi.ogg','MWI.svg','https://es.wikipedia.org/wiki/Malaui','https://en.wikipedia.org/wiki/Malawi')");
        db.execSQL("INSERT INTO paises VALUES('MY','MYS','Malaysia','Malasia','MYR',NULL,'MYS.svg','https://es.wikipedia.org/wiki/Malasia','https://en.wikipedia.org/wiki/Malaysia')");
        db.execSQL("INSERT INTO paises VALUES('MV','MDV','Maldives','Maldivas','MVR','https://upload.wikimedia.org/wikipedia/commons/c/c4/Gaumii_salaam.ogg','MDV.svg','https://es.wikipedia.org/wiki/Maldivas','https://en.wikipedia.org/wiki/Maldives')");
        db.execSQL("INSERT INTO paises VALUES('ML','MLI','Mali','Malí','XOF',NULL,'MLI.svg','https://es.wikipedia.org/wiki/Mal%C3%AD','https://en.wikipedia.org/wiki/Mali')");
        db.execSQL("INSERT INTO paises VALUES('MT','MLT','Malta','Malta','EUR','https://upload.wikimedia.org/wikipedia/commons/6/6d/Malta_National_Anthem.ogg','MLT.svg','https://es.wikipedia.org/wiki/Malta','https://en.wikipedia.org/wiki/Malta')");
        db.execSQL("INSERT INTO paises VALUES('MH','MHL','Marshall Islands','Islas Marshall','USD','https://upload.wikimedia.org/wikipedia/commons/a/a3/National_Anthem_of_Marshall_Islands_by_US_Navy_Band.ogg','MHL.svg','https://es.wikipedia.org/wiki/Islas_Marshall','https://en.wikipedia.org/wiki/Marshall_Islands')");
        db.execSQL("INSERT INTO paises VALUES('MQ','MTQ','Martinique','Martinica','EUR',NULL,'MTQ.svg','https://es.wikipedia.org/wiki/Martinica','https://en.wikipedia.org/wiki/Martinique')");
        db.execSQL("INSERT INTO paises VALUES('MR','MRT','Mauritania','Mauritania','MRO','https://upload.wikimedia.org/wikipedia/commons/1/12/National_Anthem_of_Mauritania_by_US_Navy_Band.ogg','MRT.svg','https://es.wikipedia.org/wiki/Mauritania','https://en.wikipedia.org/wiki/Mauritania')");
        db.execSQL("INSERT INTO paises VALUES('MU','MUS','Mauritius','Mauricio','MUR','https://upload.wikimedia.org/wikipedia/commons/4/45/National_Anthem_of_Mauritius_by_US_Navy_Band.ogg','MUS.svg','https://es.wikipedia.org/wiki/Mauricio','https://en.wikipedia.org/wiki/Mauritius')");
        db.execSQL("INSERT INTO paises VALUES('YT','MYT','Mayotte','Mayotte','EUR',NULL,'MYT.svg','https://es.wikipedia.org/wiki/Mayotte','https://en.wikipedia.org/wiki/Mayotte')");
        db.execSQL("INSERT INTO paises VALUES('MX','MEX','Mexico','México','MXN-MXV','https://upload.wikimedia.org/wikipedia/commons/9/9d/Himno_Nacional_Mexicano_instrumental.ogg','MEX.svg','https://es.wikipedia.org/wiki/M%C3%A9xico','https://en.wikipedia.org/wiki/Mexico')");
        db.execSQL("INSERT INTO paises VALUES('FM','FSM','Micronesia (Federated States of)','Micronesia','USD','https://upload.wikimedia.org/wikipedia/commons/6/6e/Micronesia_National_Anthem.ogg','FSM.svg','https://es.wikipedia.org/wiki/Estados_Federados_de_Micronesia','https://en.wikipedia.org/wiki/Micronesia_(Federated_States_of)')");
        db.execSQL("INSERT INTO paises VALUES('MD','MDA','Moldova (Republic of)','Moldavia','MDL','https://upload.wikimedia.org/wikipedia/commons/1/19/Imnul_Republicii_Moldova_versiune_coral.ogg','MDA.svg','https://es.wikipedia.org/wiki/Moldavia','https://en.wikipedia.org/wiki/Moldova_(Republic_of)')");
        db.execSQL("INSERT INTO paises VALUES('MC','MCO','Monaco','Mónaco','EUR','https://upload.wikimedia.org/wikipedia/commons/c/c2/Monaco_National_Anthem.ogg','MCO.svg','https://es.wikipedia.org/wiki/M%C3%B3naco','https://en.wikipedia.org/wiki/Monaco')");
        db.execSQL("INSERT INTO paises VALUES('MN','MNG','Mongolia','Mongolia','MNT','https://upload.wikimedia.org/wikipedia/commons/a/a2/National_anthem_of_Mongolia_2006_official-instrumental.ogg','MNG.svg','https://es.wikipedia.org/wiki/Mongolia','https://en.wikipedia.org/wiki/Mongolia')");
        db.execSQL("INSERT INTO paises VALUES('ME','MNE','Montenegro','Montenegro','EUR','https://upload.wikimedia.org/wikipedia/commons/a/a2/National_Anthem_of_Montenegro.ogg','MNE.svg','https://es.wikipedia.org/wiki/Montenegro','https://en.wikipedia.org/wiki/Montenegro')");
        db.execSQL("INSERT INTO paises VALUES('MS','MSR','Montserrat','Montserrat','XCD','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','MSR.svg','https://es.wikipedia.org/wiki/Montserrat','https://en.wikipedia.org/wiki/Montserrat')");
        db.execSQL("INSERT INTO paises VALUES('MA','MAR','Morocco','Marruecos','MAD','https://upload.wikimedia.org/wikipedia/commons/3/3f/National_Anthem_of_Morocco.ogg','MAR.svg','https://es.wikipedia.org/wiki/Marruecos','https://en.wikipedia.org/wiki/Morocco')");
        db.execSQL("INSERT INTO paises VALUES('MZ','MOZ','Mozambique','Mozambique','MZN','https://upload.wikimedia.org/wikipedia/commons/0/0c/National_Anthem_of_Mozambique_by_US_Navy_Band.ogg','MOZ.svg','https://es.wikipedia.org/wiki/Mozambique','https://en.wikipedia.org/wiki/Mozambique')");
        db.execSQL("INSERT INTO paises VALUES('MM','MMR','Myanmar','Myanmar','MMK','https://upload.wikimedia.org/wikipedia/commons/a/ae/US_NAVY_Band_-_Kaba_Ma_Kyei.ogg','MMR.svg','https://es.wikipedia.org/wiki/Birmania','https://en.wikipedia.org/wiki/Myanmar')");
        db.execSQL("INSERT INTO paises VALUES('NA','NAM','Namibia','Namibia','NAD-ZAR',NULL,'NAM.svg','https://es.wikipedia.org/wiki/Namibia','https://en.wikipedia.org/wiki/Namibia')");
        db.execSQL("INSERT INTO paises VALUES('NR','NRU','Nauru','Nauru','AUD',NULL,'NRU.svg','https://es.wikipedia.org/wiki/Nauru','https://en.wikipedia.org/wiki/Nauru')");
        db.execSQL("INSERT INTO paises VALUES('NP','NPL','Nepal','Nepal','NPR','https://upload.wikimedia.org/wikipedia/commons/a/ae/Nepal_anthem.ogg','NPL.svg','https://es.wikipedia.org/wiki/Nepal','https://en.wikipedia.org/wiki/Nepal')");
        db.execSQL("INSERT INTO paises VALUES('NL','NLD','Netherlands','Países Bajos','EUR','https://upload.wikimedia.org/wikipedia/commons/2/2e/United_States_Navy_Band_-_Het_Wilhelmus.ogg','NLD.svg','https://es.wikipedia.org/wiki/Pa%C3%ADses_Bajos','https://en.wikipedia.org/wiki/Netherlands')");
        db.execSQL("INSERT INTO paises VALUES('NC','NCL','New Caledonia','Nueva Caledonia','XPF',NULL,'NCL.svg','https://es.wikipedia.org/wiki/Nueva_Caledonia','https://en.wikipedia.org/wiki/New_Caledonia')");
        db.execSQL("INSERT INTO paises VALUES('NZ','NZL','New Zealand','Nueva Zelanda','NZD','https://upload.wikimedia.org/wikipedia/commons/d/d6/God_Defend_New_Zealand_instrumental.ogg','NZL.svg','https://es.wikipedia.org/wiki/Nueva_Zelanda','https://en.wikipedia.org/wiki/New_Zealand')");
        db.execSQL("INSERT INTO paises VALUES('NI','NIC','Nicaragua','Nicaragua','NIO','https://upload.wikimedia.org/wikipedia/commons/d/db/National_Anthem_of_Nicaragua.ogg','NIC.svg','https://es.wikipedia.org/wiki/Nicaragua','https://en.wikipedia.org/wiki/Nicaragua')");
        db.execSQL("INSERT INTO paises VALUES('NE','NER','Niger','Níger','XOF',NULL,'NER.svg','https://es.wikipedia.org/wiki/N%C3%ADger','https://en.wikipedia.org/wiki/Niger')");
        db.execSQL("INSERT INTO paises VALUES('NG','NGA','Nigeria','Nigeria','NGN','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_Arise_O_Compatriots.ogg','NGA.svg','https://es.wikipedia.org/wiki/Nigeria','https://en.wikipedia.org/wiki/Nigeria')");
        db.execSQL("INSERT INTO paises VALUES('NU','NIU','Niue','Niue','NZD',NULL,'NIU.svg','https://es.wikipedia.org/wiki/Niue','https://en.wikipedia.org/wiki/Niue')");
        db.execSQL("INSERT INTO paises VALUES('NF','NFK','Norfolk Island','Norfolk','AUD',NULL,'NFK.svg','https://es.wikipedia.org/wiki/Isla_Norfolk','https://en.wikipedia.org/wiki/Norfolk_Island')");
        db.execSQL("INSERT INTO paises VALUES('MP','MNP','Northern Mariana Islands','Islas Marianas del Norte','USD',NULL,'MNP.svg','https://es.wikipedia.org/wiki/Islas_Marianas_del_Norte','https://en.wikipedia.org/wiki/Northern_Mariana_Islands')");
        db.execSQL("INSERT INTO paises VALUES('NO','NOR','Norway','Noruega','NOK','https://upload.wikimedia.org/wikipedia/commons/f/f6/Norway_%28National_Anthem%29.ogg','NOR.svg','https://es.wikipedia.org/wiki/Noruega','https://en.wikipedia.org/wiki/Norway')");
        db.execSQL("INSERT INTO paises VALUES('OM','OMN','Oman','Omán','OMR','https://upload.wikimedia.org/wikipedia/commons/5/5a/Peace_to_the_Sultan_%28%D9%86%D8%B4%D9%8A%D8%AF_%D8%A7%D9%84%D8%B3%D9%84%D8%A7%D9%85_%D8%A7%D9%84%D8%B3%D9%84%D8%B7%D8%A7%D9%86%D9%8A%29.ogg','OMN.svg','https://es.wikipedia.org/wiki/Om%C3%A1n','https://en.wikipedia.org/wiki/Oman')");
        db.execSQL("INSERT INTO paises VALUES('PK','PAK','Pakistan','Pakistán','PKR','https://upload.wikimedia.org/wikipedia/commons/a/a7/National_anthem_of_Pakistan.OGG','PAK.svg','https://es.wikipedia.org/wiki/Pakist%C3%A1n','https://en.wikipedia.org/wiki/Pakistan')");
        db.execSQL("INSERT INTO paises VALUES('PW','PLW','Palau','Palaos','USD','https://upload.wikimedia.org/wikipedia/commons/a/ac/National_Anthem_of_Palau_by_US_Navy_Band.ogg','PLW.svg','https://es.wikipedia.org/wiki/Palaos','https://en.wikipedia.org/wiki/Palau')");
        db.execSQL("INSERT INTO paises VALUES('PS','PSE','Palestine, State of','Palestina','XXX','https://upload.wikimedia.org/wikipedia/commons/9/97/National_Anthem_of_Palestine_%28Vocal%29.ogg','PSE.svg','https://es.wikipedia.org/wiki/Estado_de_Palestina','https://en.wikipedia.org/wiki/State_of_Palestine')");
        db.execSQL("INSERT INTO paises VALUES('PA','PAN','Panama','Panamá','PAB-USD','https://upload.wikimedia.org/wikipedia/commons/4/4a/Panama_National_Anthem.ogg','PAN.svg','https://es.wikipedia.org/wiki/Panam%C3%A1','https://en.wikipedia.org/wiki/Panama')");
        db.execSQL("INSERT INTO paises VALUES('PG','PNG','Papua New Guinea','Papúa Nueva Guinea','PGK','https://upload.wikimedia.org/wikipedia/commons/d/df/National_Anthem_of_Papua_New_Guinea_by_US_Navy_Band.ogg','PNG.svg','https://es.wikipedia.org/wiki/Pap%C3%BAa_Nueva_Guinea','https://en.wikipedia.org/wiki/Papua_New_Guinea')");
        db.execSQL("INSERT INTO paises VALUES('PY','PRY','Paraguay','Paraguay','PYG','https://upload.wikimedia.org/wikipedia/commons/f/fd/Paraguay_National_Anthem.ogg','PRY.svg','https://es.wikipedia.org/wiki/Paraguay','https://en.wikipedia.org/wiki/Paraguay')");
        db.execSQL("INSERT INTO paises VALUES('PE','PER','Peru','Perú','PEN','https://upload.wikimedia.org/wikipedia/commons/c/cc/United_States_Navy_Band_-_Marcha_Nacional_del_Per%C3%BA.ogg','PER.svg','https://es.wikipedia.org/wiki/Per%C3%BA','https://en.wikipedia.org/wiki/Peru')");
        db.execSQL("INSERT INTO paises VALUES('PH','PHL','Philippines','Filipinas','PHP','https://upload.wikimedia.org/wikipedia/commons/2/2b/Lupang_Hinirang_instrumental.ogg','PHL.svg','https://es.wikipedia.org/wiki/Filipinas','https://en.wikipedia.org/wiki/Philippines')");
        db.execSQL("INSERT INTO paises VALUES('PN','PCN','Pitcairn','Islas Pitcairn','NZD','https://upload.wikimedia.org/wikipedia/commons/8/8d/United_States_Navy_Band_-_La_Borinque%C3%B1a.ogg','PCN.svg','https://es.wikipedia.org/wiki/Islas_Pitcairn','https://en.wikipedia.org/wiki/Pitcairn')");
        db.execSQL("INSERT INTO paises VALUES('PL','POL','Poland','Polonia','PLN','https://upload.wikimedia.org/wikipedia/commons/b/b1/Mazurek_Dabrowskiego.ogg','POL.svg','https://es.wikipedia.org/wiki/Polonia','https://en.wikipedia.org/wiki/Poland')");
        db.execSQL("INSERT INTO paises VALUES('PT','PRT','Portugal','Portugal','EUR','https://upload.wikimedia.org/wikipedia/commons/5/58/A_Portuguesa.ogg','PRT.svg','https://es.wikipedia.org/wiki/Portugal','https://en.wikipedia.org/wiki/Portugal')");
        db.execSQL("INSERT INTO paises VALUES('PR','PRI','Puerto Rico','Puerto Rico','USD','https://upload.wikimedia.org/wikipedia/commons/8/8d/United_States_Navy_Band_-_La_Borinque%C3%B1a.ogg','PRI.svg','https://es.wikipedia.org/wiki/Puerto_Rico','https://en.wikipedia.org/wiki/Puerto_Rico')");
        db.execSQL("INSERT INTO paises VALUES('QA','QAT','Qatar','Catar','QAR','https://upload.wikimedia.org/wikipedia/commons/e/ec/National_anthem_of_Qatar.ogg','QAT.svg','https://es.wikipedia.org/wiki/Catar','https://en.wikipedia.org/wiki/Qatar')");
        db.execSQL("INSERT INTO paises VALUES('RE','REU','Réunion','Reunión','EUR',NULL,'REU.svg','https://es.wikipedia.org/wiki/Reuni%C3%B3n_(departamento_de_Francia)','https://en.wikipedia.org/wiki/R%C3%A9union')");
        db.execSQL("INSERT INTO paises VALUES('RO','ROU','Romania','Rumania','RON','https://upload.wikimedia.org/wikipedia/commons/7/77/Desteapta-te%2C_romane%21.ogg','ROU.svg','https://es.wikipedia.org/wiki/Rumania','https://en.wikipedia.org/wiki/Romania')");
        db.execSQL("INSERT INTO paises VALUES('RU','RUS','Russian Federation','Rusia','RUB','https://upload.wikimedia.org/wikipedia/commons/0/02/National_Anthem_of_Russia_%282000%29%2C_three_verses.ogg','RUS.svg','https://es.wikipedia.org/wiki/Rusia','https://en.wikipedia.org/wiki/Russian_Federation')");
        db.execSQL("INSERT INTO paises VALUES('RW','RWA','Rwanda','Ruanda','RWF','https://upload.wikimedia.org/wikipedia/commons/0/0e/Hymne_National_du_Rwanda.ogg','RWA.svg','https://es.wikipedia.org/wiki/Ruanda','https://en.wikipedia.org/wiki/Rwanda')");
        db.execSQL("INSERT INTO paises VALUES('BL','BLM','Saint Barthélemy','San Bartolomé','EUR','https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg','BLM.svg','https://es.wikipedia.org/wiki/San_Bartolom%C3%A9_(Francia)','https://en.wikipedia.org/wiki/Saint_Barth%C3%A9lemy')");
        db.execSQL("INSERT INTO paises VALUES('SH','SHN','Saint Helena, Ascension and Tristan da Cunha','Santa Elena, Ascensión y Tristán de Acuña','SHP','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','SHN.svg','https://es.wikipedia.org/wiki/Santa_Elena,_Ascensi%C3%B3n_y_Trist%C3%A1n_de_Acu%C3%B1a','https://en.wikipedia.org/wiki/Saint_Helena,_Ascension_and_Tristan_da_Cunha')");
        db.execSQL("INSERT INTO paises VALUES('KN','KNA','Saint Kitts and Nevis','San Cristóbal y Nieves','XCD','https://upload.wikimedia.org/wikipedia/commons/3/3f/United_States_Navy_Band_-_O_Land_of_Beauty.ogg','KNA.svg','https://es.wikipedia.org/wiki/San_Crist%C3%B3bal_y_Nieves','https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis')");
        db.execSQL("INSERT INTO paises VALUES('LC','LCA','Saint Lucia','Santa Lucía','XCD',NULL,'LCA.svg','https://es.wikipedia.org/wiki/Santa_Luc%C3%ADa','https://en.wikipedia.org/wiki/Saint_Lucia')");
        db.execSQL("INSERT INTO paises VALUES('MF','MAF','Saint Martin (French part)','San Martín','EUR','https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg','MAF.svg','https://es.wikipedia.org/wiki/San_Mart%C3%ADn_(Francia)','https://en.wikipedia.org/wiki/Saint_Martin_(French_part)')");
        db.execSQL("INSERT INTO paises VALUES('PM','SPM','Saint Pierre and Miquelon','San Pedro y Miquelón','EUR','https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg','SPM.svg','https://es.wikipedia.org/wiki/San_Pedro_y_Miquel%C3%B3n','https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon')");
        db.execSQL("INSERT INTO paises VALUES('VC','VCT','Saint Vincent and the Grenadines','San Vicente y las Granadinas','XCD',NULL,'VCT.svg','https://es.wikipedia.org/wiki/San_Vicente_y_las_Granadinas','https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines')");
        db.execSQL("INSERT INTO paises VALUES('WS','WSM','Samoa','Samoa','USD-WST',NULL,'WSM.svg','https://es.wikipedia.org/wiki/Samoa','https://en.wikipedia.org/wiki/Samoa')");
        db.execSQL("INSERT INTO paises VALUES('SM','SMR','San Marino','San Marino','EUR',NULL,'SMR.svg','https://es.wikipedia.org/wiki/San_Marino','https://en.wikipedia.org/wiki/San_Marino')");
        db.execSQL("INSERT INTO paises VALUES('ST','STP','Sao Tome and Principe','Santo Tomé y Príncipe','STD','https://upload.wikimedia.org/wikipedia/commons/e/ed/National_Anthem_of_Sao_Tome_and_Principe_by_US_Navy_Band.ogg','STP.svg','https://es.wikipedia.org/wiki/Santo_Tom%C3%A9_y_Pr%C3%ADncipe','https://en.wikipedia.org/wiki/Sao_Tome_and_Principe')");
        db.execSQL("INSERT INTO paises VALUES('SA','SAU','Saudi Arabia','Arabia Saudita','SAR','https://upload.wikimedia.org/wikipedia/commons/f/f0/Aash_Al_Maleek_instrumental.ogg','SAU.svg','https://es.wikipedia.org/wiki/Arabia_Saudita','https://en.wikipedia.org/wiki/Saudi_Arabia')");
        db.execSQL("INSERT INTO paises VALUES('SN','SEN','Senegal','Senegal','XOF','https://upload.wikimedia.org/wikipedia/commons/8/8c/National_Anthem_of_Senegal.ogg','SEN.svg','https://es.wikipedia.org/wiki/Senegal','https://en.wikipedia.org/wiki/Senegal')");
        db.execSQL("INSERT INTO paises VALUES('RS','SRB','Serbia','Serbia','RSD','https://upload.wikimedia.org/wikipedia/commons/d/d0/Serbian_National_Anthem_instrumental.ogg','SRB.svg','https://es.wikipedia.org/wiki/Serbia','https://en.wikipedia.org/wiki/Serbia')");
        db.execSQL("INSERT INTO paises VALUES('SC','SYC','Seychelles','Seychelles','SCR','https://upload.wikimedia.org/wikipedia/commons/6/66/National_Anthem_of_Seychelles_by_US_Navy_Band.ogg','SYC.svg','https://es.wikipedia.org/wiki/Seychelles','https://en.wikipedia.org/wiki/Seychelles')");
        db.execSQL("INSERT INTO paises VALUES('SL','SLE','Sierra Leone','Sierra Leona','SLL','https://upload.wikimedia.org/wikipedia/commons/5/57/National_Anthem_of_Sierra_Leone_by_US_Navy_Band.ogg','SLE.svg','https://es.wikipedia.org/wiki/Sierra_Leona','https://en.wikipedia.org/wiki/Sierra_Leone')");
        db.execSQL("INSERT INTO paises VALUES('SG','SGP','Singapore','Singapur','SGD','https://upload.wikimedia.org/wikipedia/commons/7/74/Majulah_Singapura.ogg','SGP.svg','https://es.wikipedia.org/wiki/Singapur','https://en.wikipedia.org/wiki/Singapore')");
        db.execSQL("INSERT INTO paises VALUES('SX','SXM','Sint Maarten (Dutch part)','Sint Maarten','ANG',NULL,'SXM.svg','https://es.wikipedia.org/wiki/Sint_Maarten','https://en.wikipedia.org/wiki/Sint_Maarten_(Dutch_part)')");
        db.execSQL("INSERT INTO paises VALUES('SK','SVK','Slovakia','Eslovaquia','EUR','https://upload.wikimedia.org/wikipedia/commons/b/b5/Slovak_anthem1.ogg','SVK.svg','https://es.wikipedia.org/wiki/Eslovaquia','https://en.wikipedia.org/wiki/Slovakia')");
        db.execSQL("INSERT INTO paises VALUES('SI','SVN','Slovenia','Eslovenia','EUR','https://upload.wikimedia.org/wikipedia/commons/d/de/Zdravljica.ogg','SVN.svg','https://es.wikipedia.org/wiki/Eslovenia','https://en.wikipedia.org/wiki/Slovenia')");
        db.execSQL("INSERT INTO paises VALUES('SB','SLB','Solomon Islands','Islas Salomón','SBD',NULL,'SLB.svg','https://es.wikipedia.org/wiki/Islas_Salom%C3%B3n','https://en.wikipedia.org/wiki/Solomon_Islands')");
        db.execSQL("INSERT INTO paises VALUES('SO','SOM','Somalia','Somalia','SOS','https://upload.wikimedia.org/wikipedia/commons/5/5a/QolobaaCalankeed.ogg','SOM.svg','https://es.wikipedia.org/wiki/Somalia','https://en.wikipedia.org/wiki/Somalia')");
        db.execSQL("INSERT INTO paises VALUES('ZA','ZAF','South Africa','Sudáfrica','ZAR','https://upload.wikimedia.org/wikipedia/commons/7/7e/South_Africa_National_Anthem.ogg','ZAF.svg','https://es.wikipedia.org/wiki/Sud%C3%A1frica','https://en.wikipedia.org/wiki/South_Africa')");
        db.execSQL("INSERT INTO paises VALUES('GS','SGS','South Georgia and the South Sandwich Islands','Islas Georgias del Sur y Sandwich del Sur','XXX','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','SGS.svg','https://es.wikipedia.org/wiki/Islas_Georgias_del_Sur_y_Sandwich_del_Sur_(territorio_brit%C3%A1nico_de_ultramar)','https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands')");
        db.execSQL("INSERT INTO paises VALUES('SS','SSD','South Sudan','Sudán del Sur','SSP','https://upload.wikimedia.org/wikipedia/commons/0/03/South_Sudan_Oyee%21.ogg','SSD.svg','https://es.wikipedia.org/wiki/Sud%C3%A1n_del_Sur','https://en.wikipedia.org/wiki/South_Sudan')");
        db.execSQL("INSERT INTO paises VALUES('ES','ESP','Spain','España','EUR','https://upload.wikimedia.org/wikipedia/commons/c/c8/Marcha_Real-Royal_March_by_US_Navy_Band.ogg','ESP.svg','https://es.wikipedia.org/wiki/Espa%C3%B1a','https://en.wikipedia.org/wiki/Spain')");
        db.execSQL("INSERT INTO paises VALUES('LK','LKA','Sri Lanka','Sri Lanka','LKR','https://upload.wikimedia.org/wikipedia/commons/4/47/National_Anthem_of_Sri_Lanka_by_US_Navy_Band.ogg','LKA.svg','https://es.wikipedia.org/wiki/Sri_Lanka','https://en.wikipedia.org/wiki/Sri_Lanka')");
        db.execSQL("INSERT INTO paises VALUES('SD','SDN','Sudan','Sudán','SDG-SSP','https://upload.wikimedia.org/wikipedia/commons/7/75/Sudan.ogg','SDN.svg','https://es.wikipedia.org/wiki/Sud%C3%A1n','https://en.wikipedia.org/wiki/Sudan')");
        db.execSQL("INSERT INTO paises VALUES('SR','SUR','Suriname','Surinam','SRD',NULL,'SUR.svg','https://es.wikipedia.org/wiki/Surinam','https://en.wikipedia.org/wiki/Suriname')");
        db.execSQL("INSERT INTO paises VALUES('SJ','SJM','Svalbard and Jan Mayen','Svalbard y Jan Mayen','NOK',NULL,'SJM.svg','https://es.wikipedia.org/wiki/Svalbard_y_Jan_Mayen','https://en.wikipedia.org/wiki/Svalbard_and_Jan_Mayen')");
        db.execSQL("INSERT INTO paises VALUES('SZ','SWZ','Swaziland','Suazilandia','SZL','https://upload.wikimedia.org/wikipedia/commons/9/97/Swaziland.ogg','SWZ.svg','https://es.wikipedia.org/wiki/Suazilandia','https://en.wikipedia.org/wiki/Swaziland')");
        db.execSQL("INSERT INTO paises VALUES('SE','SWE','Sweden','Suecia','SEK','https://upload.wikimedia.org/wikipedia/commons/0/02/United_States_Navy_Band_-_Sweden.ogg','SWE.svg','https://es.wikipedia.org/wiki/Suecia','https://en.wikipedia.org/wiki/Sweden')");
        db.execSQL("INSERT INTO paises VALUES('CH','CHE','Switzerland','Suiza','CHE-CHF-CHW','https://upload.wikimedia.org/wikipedia/commons/0/00/Swiss_Psalm.ogg','CHE.svg','https://es.wikipedia.org/wiki/Suiza','https://en.wikipedia.org/wiki/Switzerland')");
        db.execSQL("INSERT INTO paises VALUES('SY','SYR','Syrian Arab Republic','Siria','SYP','https://upload.wikimedia.org/wikipedia/commons/f/fc/National_Anthem_of_Syria.ogg','SYR.svg','https://es.wikipedia.org/wiki/Siria','https://en.wikipedia.org/wiki/Syrian_Arab_Republic')");
        db.execSQL("INSERT INTO paises VALUES('TW','TWN','Taiwan, Province of China','Taiwán (República de China)','TWD','https://upload.wikimedia.org/wikipedia/commons/9/98/National_Anthem_of_the_Republic_of_China.ogg','TWN.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_de_China','https://en.wikipedia.org/wiki/Taiwan,_Province_of_China')");
        db.execSQL("INSERT INTO paises VALUES('TJ','TJK','Tajikistan','Tayikistán','TJS','https://upload.wikimedia.org/wikipedia/commons/b/b9/Tajikistan_anthem.ogg','TJK.svg','https://es.wikipedia.org/wiki/Tayikist%C3%A1n','https://en.wikipedia.org/wiki/Tajikistan')");
        db.execSQL("INSERT INTO paises VALUES('TZ','TZA','Tanzania, United Republic of','Tanzania','TZS','https://upload.wikimedia.org/wikipedia/commons/2/22/National_Anthem_of_Tanzania_by_US_Navy_Band.ogg','TZA.svg','https://es.wikipedia.org/wiki/Tanzania','https://en.wikipedia.org/wiki/Tanzania,_United_Republic_of')");
        db.execSQL("INSERT INTO paises VALUES('TH','THA','Thailand','Tailandia','THB','https://upload.wikimedia.org/wikipedia/commons/f/f3/Thai_National_Anthem_-_US_Navy_Band.ogg','THA.svg','https://es.wikipedia.org/wiki/Tailandia','https://en.wikipedia.org/wiki/Thailand')");
        db.execSQL("INSERT INTO paises VALUES('TL','TLS','Timor-Leste','Timor Oriental','USD',NULL,'TLS.svg','https://es.wikipedia.org/wiki/Timor_Oriental','https://en.wikipedia.org/wiki/Timor-Leste')");
        db.execSQL("INSERT INTO paises VALUES('TG','TGO','Togo','Togo','XOF','https://upload.wikimedia.org/wikipedia/commons/1/19/National_Anthem_of_Togo.ogg','TGO.svg','https://es.wikipedia.org/wiki/Togo','https://en.wikipedia.org/wiki/Togo')");
        db.execSQL("INSERT INTO paises VALUES('TK','TKL','Tokelau','Tokelau','NZD',NULL,'TKL.svg','https://es.wikipedia.org/wiki/Tokelau','https://en.wikipedia.org/wiki/Tokelau')");
        db.execSQL("INSERT INTO paises VALUES('TO','TON','Tonga','Tonga','TOP',NULL,'TON.svg','https://es.wikipedia.org/wiki/Tonga','https://en.wikipedia.org/wiki/Tonga')");
        db.execSQL("INSERT INTO paises VALUES('TT','TTO','Trinidad and Tobago','Trinidad y Tobago','TTD','https://upload.wikimedia.org/wikipedia/commons/f/f7/National_Anthem_of_Trinidad_and_Tobago_by_US_Navy_Band.ogg','TTO.svg','https://es.wikipedia.org/wiki/Trinidad_y_Tobago','https://en.wikipedia.org/wiki/Trinidad_and_Tobago')");
        db.execSQL("INSERT INTO paises VALUES('TN','TUN','Tunisia','Túnez','TND','https://upload.wikimedia.org/wikipedia/commons/2/23/Humat_al-Hima.ogg','TUN.svg','https://es.wikipedia.org/wiki/T%C3%BAnez','https://en.wikipedia.org/wiki/Tunisia')");
        db.execSQL("INSERT INTO paises VALUES('TR','TUR','Turkey','Turquía','TRY','https://upload.wikimedia.org/wikipedia/commons/9/99/Istikl%C3%A2l_Marsi_instrumetal.ogg','TUR.svg','https://es.wikipedia.org/wiki/Turqu%C3%ADa','https://en.wikipedia.org/wiki/Turkey')");
        db.execSQL("INSERT INTO paises VALUES('TM','TKM','Turkmenistan','Turkmenistán','TMT','https://upload.wikimedia.org/wikipedia/commons/3/3e/US_Navy_Band_-_National_Anthem_of_Turkmenistan.ogg','TKM.svg','https://es.wikipedia.org/wiki/Turkmenist%C3%A1n','https://en.wikipedia.org/wiki/Turkmenistan')");
        db.execSQL("INSERT INTO paises VALUES('TC','TCA','Turks and Caicos Islands','Islas Turcas y Caicos','USD','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','TCA.svg','https://es.wikipedia.org/wiki/Islas_Turcas_y_Caicos','https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands')");
        db.execSQL("INSERT INTO paises VALUES('TV','TUV','Tuvalu','Tuvalu','AUD','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','TUV.svg','https://es.wikipedia.org/wiki/Tuvalu','https://en.wikipedia.org/wiki/Tuvalu')");
        db.execSQL("INSERT INTO paises VALUES('UG','UGA','Uganda','Uganda','UGX','https://upload.wikimedia.org/wikipedia/commons/1/1f/Uganda_flag_and_national_anthem_-_Oh_Uganda_Land_o.ogg','UGA.svg','https://es.wikipedia.org/wiki/Uganda','https://en.wikipedia.org/wiki/Uganda')");
        db.execSQL("INSERT INTO paises VALUES('UA','UKR','Ukraine','Ucrania','UAH','https://upload.wikimedia.org/wikipedia/commons/f/ff/Anthem_of_Ukraine_instrumental.ogg','UKR.svg','https://es.wikipedia.org/wiki/Ucrania','https://en.wikipedia.org/wiki/Ukraine')");
        db.execSQL("INSERT INTO paises VALUES('AE','ARE','United Arab Emirates','Emiratos Árabes Unidos','AED',NULL,'ARE.svg','https://es.wikipedia.org/wiki/Emiratos_%C3%81rabes_Unidos','https://en.wikipedia.org/wiki/United_Arab_Emirates')");
        db.execSQL("INSERT INTO paises VALUES('GB','GBR','United Kingdom of Great Britain and Northern Ireland','Reino Unido','GBP','https://upload.wikimedia.org/wikipedia/commons/d/de/United_States_Navy_Band_-_God_Save_the_Queen.ogg','GBR.svg','https://es.wikipedia.org/wiki/Reino_Unido','https://en.wikipedia.org/wiki/United_Kingdom_of_Great_Britain_and_Northern_Ireland')");
        db.execSQL("INSERT INTO paises VALUES('US','USA','United States of America','Estados Unidos','USD-USN','https://upload.wikimedia.org/wikipedia/commons/8/80/The_Star-Spangled_Banner_-_U.S._Army_1st_Armored_Division_Band.ogg','USA.svg','https://es.wikipedia.org/wiki/Estados_Unidos','https://en.wikipedia.org/wiki/United_States_of_America')");
        db.execSQL("INSERT INTO paises VALUES('UM','UMI','United States Minor Outlying Islands','Islas ultramarinas de Estados Unidos','USD',NULL,'UMI.svg','https://es.wikipedia.org/wiki/Islas_ultramarinas_de_Estados_Unidos','https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands')");
        db.execSQL("INSERT INTO paises VALUES('UY','URY','Uruguay','Uruguay','UYI-UYU','https://upload.wikimedia.org/wikipedia/commons/b/bb/HimnoNacionalUruguay.ogg','URY.svg','https://es.wikipedia.org/wiki/Uruguay','https://en.wikipedia.org/wiki/Uruguay')");
        db.execSQL("INSERT INTO paises VALUES('UZ','UZB','Uzbekistan','Uzbekistán','UZS','https://upload.wikimedia.org/wikipedia/commons/a/af/Uzbekistan_anthem.ogg','UZB.svg','https://es.wikipedia.org/wiki/Uzbekist%C3%A1n','https://en.wikipedia.org/wiki/Uzbekistan')");
        db.execSQL("INSERT INTO paises VALUES('VU','VUT','Vanuatu','Vanuatu','VUV','https://upload.wikimedia.org/wikipedia/commons/7/7f/United_States_Navy_Band_-_Yumi%2C_Yumi%2C_Yumi.ogg','VUT.svg','https://es.wikipedia.org/wiki/Vanuatu','https://en.wikipedia.org/wiki/Vanuatu')");
        db.execSQL("INSERT INTO paises VALUES('VE','VEN','Venezuela (Bolivarian Republic of)','Venezuela','VEF','https://upload.wikimedia.org/wikipedia/commons/f/f0/United_States_Navy_Band_-_Gloria_al_Bravo_Pueblo.ogg','VEN.svg','https://es.wikipedia.org/wiki/Venezuela','https://en.wikipedia.org/wiki/Venezuela_(Bolivarian_Republic_of)')");
        db.execSQL("INSERT INTO paises VALUES('VN','VNM','Viet Nam','Vietnam','VND','https://upload.wikimedia.org/wikipedia/commons/7/73/United_States_Navy_Band_-_Ti%E1%BA%BFn_Qu%C3%A2n_Ca.ogg','VNM.svg','https://es.wikipedia.org/wiki/Vietnam','https://en.wikipedia.org/wiki/Viet_Nam')");
        db.execSQL("INSERT INTO paises VALUES('VG','VGB','Virgin Islands (British)','Islas Vírgenes Británicas','USD',NULL,'VGB.svg','https://es.wikipedia.org/wiki/Islas_V%C3%ADrgenes_Brit%C3%A1nicas','https://en.wikipedia.org/wiki/British_Virgin_Islands')");
        db.execSQL("INSERT INTO paises VALUES('VI','VIR','Virgin Islands (U.S.)','Islas Vírgenes de los Estados Unidos','USD',NULL,'VIR.svg','https://es.wikipedia.org/wiki/Islas_V%C3%ADrgenes_de_los_Estados_Unidos','https://en.wikipedia.org/wiki/United_States_Virgin_Islands')");
        db.execSQL("INSERT INTO paises VALUES('WF','WLF','Wallis and Futuna','Wallis y Futuna','XPF','https://upload.wikimedia.org/wikipedia/commons/3/30/La_Marseillaise.ogg','WLF.svg','https://es.wikipedia.org/wiki/Wallis_y_Futuna','https://en.wikipedia.org/wiki/Wallis_and_Futuna')");
        db.execSQL("INSERT INTO paises VALUES('EH','ESH','Western Sahara','República Árabe Saharaui Democrática','MAD',NULL,'ESH.svg','https://es.wikipedia.org/wiki/Rep%C3%BAblica_%C3%81rabe_Saharaui_Democr%C3%A1tica','https://en.wikipedia.org/wiki/Western_Sahara')");
        db.execSQL("INSERT INTO paises VALUES('YE','YEM','Yemen','Yemen','YER','https://upload.wikimedia.org/wikipedia/commons/1/13/United_States_Navy_Band_-_United_Republic.ogg','YEM.svg','https://es.wikipedia.org/wiki/Yemen','https://en.wikipedia.org/wiki/Yemen')");
        db.execSQL("INSERT INTO paises VALUES('ZM','ZMB','Zambia','Zambia','ZMW',NULL,'ZMB.svg','https://es.wikipedia.org/wiki/Zambia','https://en.wikipedia.org/wiki/Zambia')");
        db.execSQL("INSERT INTO paises VALUES('ZW','ZWE','Zimbabwe','Zimbabue','ZWL',NULL,'ZWE.svg','https://es.wikipedia.org/wiki/Zimbabue','https://en.wikipedia.org/wiki/Zimbabwe')");
    }
}